// =============================================================================
// BA System Context Seed — Transcrib
// Generated by: nacl-ba-context full
// Date: 2026-05-17
// =============================================================================

// -----------------------------------------------------------------------------
// SYS-001 — SystemContext
// -----------------------------------------------------------------------------
MERGE (sc:SystemContext {id: 'SYS-001'})
SET sc.name            = 'Transcrib',
    sc.goals           = [
      'Transcribe audio from large meeting video files (300–500 MB) with speaker diarization',
      'Produce a verbatim, speaker-attributed transcript with minute/second timestamps',
      'Generate a structured meeting protocol: participants, topics discussed, decisions made, action items with assignees and deadlines'
    ],
    sc.in_scope        = [
      'Video file upload (300–500 MB)',
      'Audio extraction from video',
      'Automatic Speech Recognition (ASR) with speaker diarization',
      'Verbatim transcript generation with per-speaker timestamps',
      'Meeting protocol generation: participants list, discussion topics, decisions, action items with assignees and deadlines',
      'Download / export of both artifacts by the user'
    ],
    sc.out_of_scope    = [
      'Real-time / live meeting transcription (batch processing only)',
      'Video playback or video editing',
      'User authentication and access management (no multi-tenancy assumed)',
      'Payment, billing, or subscription management',
      'Mobile native applications',
      'Integration with calendar or meeting platforms (e.g. Zoom, Teams)',
      'Sending or distributing the protocol to participants automatically'
    ],
    sc.constraints     = [
      'Input files up to 300–500 MB must be handled without timeout',
      'Tech stack is TBD — no stack-specific constraints defined yet',
      'Processing may be asynchronous due to large file sizes and ASR latency'
    ],
    sc.assumptions     = [
      '[assumption] A single user role ("Meeting Participant") covers the primary stakeholder — the person who uploads the video and retrieves artifacts',
      '[assumption] An external ASR/diarization engine is required for transcription; specific vendor/model is TBD',
      '[assumption] An LLM-based service is required for protocol generation from the transcript; specific service is TBD',
      '[assumption] A file/object storage service is required to hold large video files during processing; specific service is TBD',
      '[assumption] The system processes one video at a time per user session; queue/parallelism design is TBD'
    ],
    sc.success_criteria = [
      'User can upload a 300–500 MB video and receive a verbatim speaker-attributed transcript',
      'User can receive a structured meeting protocol with participants, topics, decisions, and action items',
      'Both artifacts are produced without manual intervention after upload',
      'Timestamps in transcript are accurate to the second'
    ],
    sc.status          = 'draft',
    sc.created         = date('2026-05-17'),
    sc.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// STK-01 — Meeting Participant (primary stakeholder)
// -----------------------------------------------------------------------------
MERGE (stk01:Stakeholder {id: 'STK-01'})
SET stk01.name     = 'Meeting Participant',
    stk01.role     = 'Primary User',
    stk01.interest = 'Uploads meeting video recordings and receives verbatim transcripts and structured meeting protocols for archiving, reporting, or task tracking';

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (stk01:Stakeholder {id: 'STK-01'})
MERGE (sc)-[:HAS_STAKEHOLDER]->(stk01);

// -----------------------------------------------------------------------------
// STK-02 — Meeting Organizer (assumption)
// -----------------------------------------------------------------------------
MERGE (stk02:Stakeholder {id: 'STK-02'})
SET stk02.name          = 'Meeting Organizer',
    stk02.role          = 'Secondary Stakeholder (assumption)',
    stk02.interest      = 'Interested in the meeting protocol artifact for distributing decisions and action items to participants; may or may not be the same person as STK-01',
    stk02.status        = 'assumption',
    stk02.assumption_note = 'Inferred because the meeting organizer is a natural consumer of the protocol artifact. In MVP scope the uploader and organizer may be the same person. Separate role added to avoid under-specifying the stakeholder space.';

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (stk02:Stakeholder {id: 'STK-02'})
MERGE (sc)-[:HAS_STAKEHOLDER]->(stk02);

// -----------------------------------------------------------------------------
// EXT-01 — Meeting Participant (User / external entity)
// -----------------------------------------------------------------------------
MERGE (ext01:ExternalEntity {id: 'EXT-01'})
SET ext01.name        = 'Meeting Participant',
    ext01.type        = 'User',
    ext01.description = 'The human user who interacts with the system UI: uploads the meeting video file and downloads the resulting verbatim transcript and meeting protocol';

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext01:ExternalEntity {id: 'EXT-01'})
MERGE (sc)-[:HAS_EXTERNAL_ENTITY]->(ext01);

// -----------------------------------------------------------------------------
// EXT-02 — ASR / Diarization Engine (assumption)
// -----------------------------------------------------------------------------
MERGE (ext02:ExternalEntity {id: 'EXT-02'})
SET ext02.name          = 'ASR / Diarization Engine',
    ext02.type          = 'ExternalSystem',
    ext02.description   = 'External automatic speech recognition and speaker diarization service. Receives audio data, returns speaker-attributed transcript segments with timestamps. Specific vendor/model is TBD.',
    ext02.status        = 'assumption',
    ext02.assumption_note = 'A dedicated ASR+diarization engine is required to produce speaker-attributed timestamped transcripts. Could be a cloud API (e.g. AssemblyAI, Whisper+pyannote) or self-hosted. Marked assumption because tech stack is TBD.';

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext02:ExternalEntity {id: 'EXT-02'})
MERGE (sc)-[:HAS_EXTERNAL_ENTITY]->(ext02);

// -----------------------------------------------------------------------------
// EXT-03 — LLM Protocol Generator (assumption)
// -----------------------------------------------------------------------------
MERGE (ext03:ExternalEntity {id: 'EXT-03'})
SET ext03.name          = 'LLM Protocol Generator',
    ext03.type          = 'ExternalSystem',
    ext03.description   = 'Large Language Model service that receives the verbatim transcript and returns a structured meeting protocol (participants, topics, decisions, action items with assignees and deadlines). Specific model/provider is TBD.',
    ext03.status        = 'assumption',
    ext03.assumption_note = 'An LLM is the natural tool for transforming a raw transcript into a structured protocol with semantic understanding. Marked assumption because tech stack and provider are TBD.';

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext03:ExternalEntity {id: 'EXT-03'})
MERGE (sc)-[:HAS_EXTERNAL_ENTITY]->(ext03);

// -----------------------------------------------------------------------------
// EXT-04 — File / Object Storage (assumption)
// -----------------------------------------------------------------------------
MERGE (ext04:ExternalEntity {id: 'EXT-04'})
SET ext04.name          = 'File / Object Storage',
    ext04.type          = 'ExternalSystem',
    ext04.description   = 'Object storage service that holds uploaded video files during asynchronous processing. Required because 300–500 MB files cannot be held in memory through the full processing pipeline.',
    ext04.status        = 'assumption',
    ext04.assumption_note = 'Large file sizes imply a dedicated storage layer for durability across async processing steps. Could be S3, local filesystem, or similar. Marked assumption because tech stack is TBD.';

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext04:ExternalEntity {id: 'EXT-04'})
MERGE (sc)-[:HAS_EXTERNAL_ENTITY]->(ext04);

// -----------------------------------------------------------------------------
// DATA FLOWS
// -----------------------------------------------------------------------------

// DFL-001 — Video file upload (User -> System)
MERGE (df001:DataFlow {id: 'DFL-001'})
SET df001.name             = 'Meeting video file upload',
    df001.direction        = 'IN',
    df001.data_description = 'Raw video file (300–500 MB) containing the meeting recording, uploaded by the user';

MERGE (ext01:ExternalEntity {id: 'EXT-01'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext01)-[:HAS_FLOW {direction: 'IN', data_description: 'Raw video file (300–500 MB) containing the meeting recording'}]->(sc);

// DFL-002 — Verbatim transcript delivery (System -> User)
MERGE (df002:DataFlow {id: 'DFL-002'})
SET df002.name             = 'Verbatim speaker-attributed transcript',
    df002.direction        = 'OUT',
    df002.data_description = 'Complete timestamped transcript with speaker labels (who said what at which minute/second), delivered to the user for download';

MERGE (ext01:ExternalEntity {id: 'EXT-01'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext01)-[:HAS_FLOW {direction: 'OUT', data_description: 'Complete timestamped transcript with speaker labels'}]->(sc);

// DFL-003 — Meeting protocol delivery (System -> User)
MERGE (df003:DataFlow {id: 'DFL-003'})
SET df003.name             = 'Meeting protocol',
    df003.direction        = 'OUT',
    df003.data_description = 'Structured meeting protocol: participants list, discussion topics, decisions made, action items with assignees and deadlines, delivered to the user for download';

MERGE (ext01:ExternalEntity {id: 'EXT-01'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext01)-[:HAS_FLOW {direction: 'OUT', data_description: 'Structured meeting protocol with participants, decisions, and action items'}]->(sc);

// DFL-004 — Audio stream sent to ASR engine (System -> ASR)
MERGE (df004:DataFlow {id: 'DFL-004'})
SET df004.name             = 'Audio data for transcription',
    df004.direction        = 'OUT',
    df004.data_description = 'Extracted audio stream (or reference to stored file) sent to the ASR/diarization engine for processing';

MERGE (ext02:ExternalEntity {id: 'EXT-02'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext02)-[:HAS_FLOW {direction: 'OUT', data_description: 'Audio stream or file reference sent for ASR and diarization'}]->(sc);

// DFL-005 — Speaker-attributed transcript segments (ASR -> System)
MERGE (df005:DataFlow {id: 'DFL-005'})
SET df005.name             = 'Speaker-attributed transcript segments',
    df005.direction        = 'IN',
    df005.data_description = 'Transcript segments returned by the ASR/diarization engine: each segment contains speaker ID, start timestamp, end timestamp, and spoken text';

MERGE (ext02:ExternalEntity {id: 'EXT-02'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext02)-[:HAS_FLOW {direction: 'IN', data_description: 'Transcript segments with speaker ID and timestamps from ASR engine'}]->(sc);

// DFL-006 — Transcript sent to LLM (System -> LLM)
MERGE (df006:DataFlow {id: 'DFL-006'})
SET df006.name             = 'Transcript text for protocol generation',
    df006.direction        = 'OUT',
    df006.data_description = 'Full verbatim transcript (with speaker labels) sent to the LLM for extraction of meeting structure: topics, decisions, action items';

MERGE (ext03:ExternalEntity {id: 'EXT-03'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext03)-[:HAS_FLOW {direction: 'OUT', data_description: 'Full verbatim transcript with speaker labels sent for protocol generation'}]->(sc);

// DFL-007 — Generated meeting protocol (LLM -> System)
MERGE (df007:DataFlow {id: 'DFL-007'})
SET df007.name             = 'Generated meeting protocol',
    df007.direction        = 'IN',
    df007.data_description = 'Structured meeting protocol returned by the LLM: participants, discussion topics, decisions, action items with assignees and deadlines';

MERGE (ext03:ExternalEntity {id: 'EXT-03'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext03)-[:HAS_FLOW {direction: 'IN', data_description: 'Structured meeting protocol from LLM with participants, decisions, and action items'}]->(sc);

// DFL-008 — Video file stored to object storage (System -> Storage)
MERGE (df008:DataFlow {id: 'DFL-008'})
SET df008.name             = 'Video file write to storage',
    df008.direction        = 'OUT',
    df008.data_description = 'Raw video/audio binary written to object storage for durable retention during asynchronous processing';

MERGE (ext04:ExternalEntity {id: 'EXT-04'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext04)-[:HAS_FLOW {direction: 'OUT', data_description: 'Raw video binary written to object storage for async processing'}]->(sc);

// DFL-009 — Video/audio file retrieved from storage (Storage -> System)
MERGE (df009:DataFlow {id: 'DFL-009'})
SET df009.name             = 'Video file retrieval from storage',
    df009.direction        = 'IN',
    df009.data_description = 'Video or extracted audio file retrieved from object storage to be passed to the ASR/diarization engine';

MERGE (ext04:ExternalEntity {id: 'EXT-04'})
MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (ext04)-[:HAS_FLOW {direction: 'IN', data_description: 'Video/audio file retrieved from object storage for ASR processing'}]->(sc);
