// =============================================================================
// BA Business Entities Seed — Transcrib
// Generated by: nacl-ba-entities full
// Date: 2026-05-17
// =============================================================================

// =============================================================================
// BUSINESS ENTITIES
// =============================================================================

// -----------------------------------------------------------------------------
// OBJ-001 — Meeting
// Root aggregate. Owns Recording, Transcript, Protocol.
// -----------------------------------------------------------------------------
MERGE (obj001:BusinessEntity {id: 'OBJ-001'})
SET obj001.name        = 'Meeting',
    obj001.description = 'Root aggregate representing a single meeting being processed through the system. Owns the uploaded recording, the resulting transcript, and the generated protocol. The top-level object referenced by all downstream entities.',
    obj001.stereotype  = 'aggregate',
    obj001.status      = 'draft',
    obj001.created     = date('2026-05-17'),
    obj001.updated     = date('2026-05-17');

// Attributes
MERGE (a01:EntityAttribute {id: 'OBJ-001-A01'})
SET a01.name = 'id',          a01.type = 'UUID',     a01.required = true,  a01.description = 'Unique meeting identifier';
MERGE (a02:EntityAttribute {id: 'OBJ-001-A02'})
SET a02.name = 'title',       a02.type = 'String',   a02.required = false, a02.description = 'Optional human-readable meeting title (user-supplied or auto-derived from filename)';
MERGE (a03:EntityAttribute {id: 'OBJ-001-A03'})
SET a03.name = 'language',    a03.type = 'Enum',     a03.required = true,  a03.description = 'Transcription language hint: RU | EN | auto';
MERGE (a04:EntityAttribute {id: 'OBJ-001-A04'})
SET a04.name = 'uploaded_at', a04.type = 'DateTime', a04.required = true,  a04.description = 'Timestamp when the upload was initiated';
MERGE (a05:EntityAttribute {id: 'OBJ-001-A05'})
SET a05.name = 'status',      a05.type = 'Enum',     a05.required = true,  a05.description = 'Current lifecycle status (see states OBJ-001-ST01..ST07)';

MERGE (obj001:BusinessEntity {id: 'OBJ-001'})
MERGE (a01:EntityAttribute {id: 'OBJ-001-A01'}) MERGE (obj001)-[:HAS_ATTRIBUTE]->(a01)
MERGE (a02:EntityAttribute {id: 'OBJ-001-A02'}) MERGE (obj001)-[:HAS_ATTRIBUTE]->(a02)
MERGE (a03:EntityAttribute {id: 'OBJ-001-A03'}) MERGE (obj001)-[:HAS_ATTRIBUTE]->(a03)
MERGE (a04:EntityAttribute {id: 'OBJ-001-A04'}) MERGE (obj001)-[:HAS_ATTRIBUTE]->(a04)
MERGE (a05:EntityAttribute {id: 'OBJ-001-A05'}) MERGE (obj001)-[:HAS_ATTRIBUTE]->(a05);

// Lifecycle states
MERGE (st01:EntityState {id: 'OBJ-001-ST01'}) SET st01.name = 'uploading',           st01.description = 'File upload is in progress';
MERGE (st02:EntityState {id: 'OBJ-001-ST02'}) SET st02.name = 'transcribing',        st02.description = 'Transcription job is queued or running';
MERGE (st03:EntityState {id: 'OBJ-001-ST03'}) SET st03.name = 'transcript_ready',    st03.description = 'Transcript has been produced and persisted';
MERGE (st04:EntityState {id: 'OBJ-001-ST04'}) SET st04.name = 'protocol_generating', st04.description = 'Protocol generation job is queued or running';
MERGE (st05:EntityState {id: 'OBJ-001-ST05'}) SET st05.name = 'protocol_ready',      st05.description = 'Protocol has been generated and persisted';
MERGE (st06:EntityState {id: 'OBJ-001-ST06'}) SET st06.name = 'edited',              st06.description = 'Protocol has been manually edited at least once; repeating state on each save';
MERGE (st07:EntityState {id: 'OBJ-001-ST07'}) SET st07.name = 'failed',              st07.description = 'A non-recoverable error occurred in the transcription or generation pipeline';

MERGE (obj001:BusinessEntity {id: 'OBJ-001'})
MERGE (st01:EntityState {id: 'OBJ-001-ST01'}) MERGE (obj001)-[:HAS_STATE]->(st01)
MERGE (st02:EntityState {id: 'OBJ-001-ST02'}) MERGE (obj001)-[:HAS_STATE]->(st02)
MERGE (st03:EntityState {id: 'OBJ-001-ST03'}) MERGE (obj001)-[:HAS_STATE]->(st03)
MERGE (st04:EntityState {id: 'OBJ-001-ST04'}) MERGE (obj001)-[:HAS_STATE]->(st04)
MERGE (st05:EntityState {id: 'OBJ-001-ST05'}) MERGE (obj001)-[:HAS_STATE]->(st05)
MERGE (st06:EntityState {id: 'OBJ-001-ST06'}) MERGE (obj001)-[:HAS_STATE]->(st06)
MERGE (st07:EntityState {id: 'OBJ-001-ST07'}) MERGE (obj001)-[:HAS_STATE]->(st07);

// State transitions
MERGE (st01:EntityState {id: 'OBJ-001-ST01'}) MERGE (st02:EntityState {id: 'OBJ-001-ST02'}) MERGE (st01)-[:TRANSITIONS_TO]->(st02);
MERGE (st02:EntityState {id: 'OBJ-001-ST02'}) MERGE (st03:EntityState {id: 'OBJ-001-ST03'}) MERGE (st02)-[:TRANSITIONS_TO]->(st03);
MERGE (st03:EntityState {id: 'OBJ-001-ST03'}) MERGE (st04:EntityState {id: 'OBJ-001-ST04'}) MERGE (st03)-[:TRANSITIONS_TO]->(st04);
MERGE (st04:EntityState {id: 'OBJ-001-ST04'}) MERGE (st05:EntityState {id: 'OBJ-001-ST05'}) MERGE (st04)-[:TRANSITIONS_TO]->(st05);
MERGE (st05:EntityState {id: 'OBJ-001-ST05'}) MERGE (st06:EntityState {id: 'OBJ-001-ST06'}) MERGE (st05)-[:TRANSITIONS_TO]->(st06);
MERGE (st06:EntityState {id: 'OBJ-001-ST06'}) MERGE (st06b:EntityState {id: 'OBJ-001-ST06'}) MERGE (st06)-[:TRANSITIONS_TO]->(st06b);
// failed is reachable from uploading, transcribing, or protocol_generating
MERGE (st01:EntityState {id: 'OBJ-001-ST01'}) MERGE (st07:EntityState {id: 'OBJ-001-ST07'}) MERGE (st01)-[:TRANSITIONS_TO]->(st07);
MERGE (st02:EntityState {id: 'OBJ-001-ST02'}) MERGE (st07:EntityState {id: 'OBJ-001-ST07'}) MERGE (st02)-[:TRANSITIONS_TO]->(st07);
MERGE (st04:EntityState {id: 'OBJ-001-ST04'}) MERGE (st07:EntityState {id: 'OBJ-001-ST07'}) MERGE (st04)-[:TRANSITIONS_TO]->(st07);

// -----------------------------------------------------------------------------
// OBJ-002 — Recording
// Uploaded video file metadata. Owned by Meeting.
// -----------------------------------------------------------------------------
MERGE (obj002:BusinessEntity {id: 'OBJ-002'})
SET obj002.name        = 'Recording',
    obj002.description = 'Metadata record for the video file uploaded by the user. Tracks original filename, size, MIME type, object storage path, and optional duration. The physical file is stored in object storage (EXT-04); this entity captures the reference and provenance.',
    obj002.stereotype  = 'entity',
    obj002.status      = 'draft',
    obj002.created     = date('2026-05-17'),
    obj002.updated     = date('2026-05-17');

MERGE (a11:EntityAttribute {id: 'OBJ-002-A01'})
SET a11.name = 'id',           a11.type = 'UUID',     a11.required = true,  a11.description = 'Unique recording identifier';
MERGE (a12:EntityAttribute {id: 'OBJ-002-A02'})
SET a12.name = 'meeting_id',   a12.type = 'UUID',     a12.required = true,  a12.description = 'Foreign key to owning Meeting (OBJ-001)';
MERGE (a13:EntityAttribute {id: 'OBJ-002-A03'})
SET a13.name = 'filename',     a13.type = 'String',   a13.required = true,  a13.description = 'Original filename as uploaded by the user';
MERGE (a14:EntityAttribute {id: 'OBJ-002-A04'})
SET a14.name = 'size_bytes',   a14.type = 'Long',     a14.required = true,  a14.description = 'File size in bytes';
MERGE (a15:EntityAttribute {id: 'OBJ-002-A05'})
SET a15.name = 'mime_type',    a15.type = 'String',   a15.required = true,  a15.description = 'MIME type of the uploaded file (e.g., video/mp4)';
MERGE (a16:EntityAttribute {id: 'OBJ-002-A06'})
SET a16.name = 'storage_path', a16.type = 'String',   a16.required = true,  a16.description = 'Object storage path/key where the raw file is persisted (EXT-04)';
MERGE (a17:EntityAttribute {id: 'OBJ-002-A07'})
SET a17.name = 'duration_sec', a17.type = 'Integer',  a17.required = false, a17.description = 'Video duration in seconds; populated after audio extraction in BP-002';
MERGE (a18:EntityAttribute {id: 'OBJ-002-A08'})
SET a18.name = 'uploaded_at',  a18.type = 'DateTime', a18.required = true,  a18.description = 'Timestamp when the upload completed successfully';

MERGE (obj002:BusinessEntity {id: 'OBJ-002'})
MERGE (a11:EntityAttribute {id: 'OBJ-002-A01'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a11)
MERGE (a12:EntityAttribute {id: 'OBJ-002-A02'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a12)
MERGE (a13:EntityAttribute {id: 'OBJ-002-A03'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a13)
MERGE (a14:EntityAttribute {id: 'OBJ-002-A04'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a14)
MERGE (a15:EntityAttribute {id: 'OBJ-002-A05'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a15)
MERGE (a16:EntityAttribute {id: 'OBJ-002-A06'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a16)
MERGE (a17:EntityAttribute {id: 'OBJ-002-A07'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a17)
MERGE (a18:EntityAttribute {id: 'OBJ-002-A08'}) MERGE (obj002)-[:HAS_ATTRIBUTE]->(a18);

// No independent lifecycle — status is tracked via Meeting.

// -----------------------------------------------------------------------------
// OBJ-003 — TranscriptionJob
// Async job that drives audio transcription. Owned by Meeting.
// -----------------------------------------------------------------------------
MERGE (obj003:BusinessEntity {id: 'OBJ-003'})
SET obj003.name        = 'TranscriptionJob',
    obj003.description = 'Async job record tracking the ASR + diarization pipeline execution for a given recording. Created when a recording is accepted and queued; updated as the pipeline progresses; used to detect failure and surface error details.',
    obj003.stereotype  = 'job',
    obj003.status      = 'draft',
    obj003.created     = date('2026-05-17'),
    obj003.updated     = date('2026-05-17');

MERGE (a21:EntityAttribute {id: 'OBJ-003-A01'})
SET a21.name = 'id',            a21.type = 'UUID',     a21.required = true,  a21.description = 'Unique job identifier';
MERGE (a22:EntityAttribute {id: 'OBJ-003-A02'})
SET a22.name = 'meeting_id',    a22.type = 'UUID',     a22.required = true,  a22.description = 'Foreign key to owning Meeting (OBJ-001)';
MERGE (a23:EntityAttribute {id: 'OBJ-003-A03'})
SET a23.name = 'recording_id',  a23.type = 'UUID',     a23.required = true,  a23.description = 'Foreign key to the Recording being processed (OBJ-002)';
MERGE (a24:EntityAttribute {id: 'OBJ-003-A04'})
SET a24.name = 'status',        a24.type = 'Enum',     a24.required = true,  a24.description = 'Job lifecycle status (see states OBJ-003-ST01..ST04)';
MERGE (a25:EntityAttribute {id: 'OBJ-003-A05'})
SET a25.name = 'error_reason',  a25.type = 'String',   a25.required = false, a25.description = 'Human-readable error description when status = failed';
MERGE (a26:EntityAttribute {id: 'OBJ-003-A06'})
SET a26.name = 'started_at',    a26.type = 'DateTime', a26.required = false, a26.description = 'Timestamp when the worker picked up the job';
MERGE (a27:EntityAttribute {id: 'OBJ-003-A07'})
SET a27.name = 'completed_at',  a27.type = 'DateTime', a27.required = false, a27.description = 'Timestamp when the job reached a terminal state (completed or failed)';

MERGE (obj003:BusinessEntity {id: 'OBJ-003'})
MERGE (a21:EntityAttribute {id: 'OBJ-003-A01'}) MERGE (obj003)-[:HAS_ATTRIBUTE]->(a21)
MERGE (a22:EntityAttribute {id: 'OBJ-003-A02'}) MERGE (obj003)-[:HAS_ATTRIBUTE]->(a22)
MERGE (a23:EntityAttribute {id: 'OBJ-003-A03'}) MERGE (obj003)-[:HAS_ATTRIBUTE]->(a23)
MERGE (a24:EntityAttribute {id: 'OBJ-003-A04'}) MERGE (obj003)-[:HAS_ATTRIBUTE]->(a24)
MERGE (a25:EntityAttribute {id: 'OBJ-003-A05'}) MERGE (obj003)-[:HAS_ATTRIBUTE]->(a25)
MERGE (a26:EntityAttribute {id: 'OBJ-003-A06'}) MERGE (obj003)-[:HAS_ATTRIBUTE]->(a26)
MERGE (a27:EntityAttribute {id: 'OBJ-003-A07'}) MERGE (obj003)-[:HAS_ATTRIBUTE]->(a27);

// Lifecycle states
MERGE (st31:EntityState {id: 'OBJ-003-ST01'}) SET st31.name = 'queued',      st31.description = 'Job has been created and is waiting for a worker';
MERGE (st32:EntityState {id: 'OBJ-003-ST02'}) SET st32.name = 'in_progress', st32.description = 'Worker has picked up the job and is running ASR/diarization';
MERGE (st33:EntityState {id: 'OBJ-003-ST03'}) SET st33.name = 'completed',   st33.description = 'Transcript produced and persisted successfully';
MERGE (st34:EntityState {id: 'OBJ-003-ST04'}) SET st34.name = 'failed',      st34.description = 'Job terminated with a non-recoverable error';

MERGE (obj003:BusinessEntity {id: 'OBJ-003'})
MERGE (st31:EntityState {id: 'OBJ-003-ST01'}) MERGE (obj003)-[:HAS_STATE]->(st31)
MERGE (st32:EntityState {id: 'OBJ-003-ST02'}) MERGE (obj003)-[:HAS_STATE]->(st32)
MERGE (st33:EntityState {id: 'OBJ-003-ST03'}) MERGE (obj003)-[:HAS_STATE]->(st33)
MERGE (st34:EntityState {id: 'OBJ-003-ST04'}) MERGE (obj003)-[:HAS_STATE]->(st34);

MERGE (st31:EntityState {id: 'OBJ-003-ST01'}) MERGE (st32:EntityState {id: 'OBJ-003-ST02'}) MERGE (st31)-[:TRANSITIONS_TO]->(st32);
MERGE (st32:EntityState {id: 'OBJ-003-ST02'}) MERGE (st33:EntityState {id: 'OBJ-003-ST03'}) MERGE (st32)-[:TRANSITIONS_TO]->(st33);
MERGE (st32:EntityState {id: 'OBJ-003-ST02'}) MERGE (st34:EntityState {id: 'OBJ-003-ST04'}) MERGE (st32)-[:TRANSITIONS_TO]->(st34);

// -----------------------------------------------------------------------------
// OBJ-004 — Transcript
// Verbatim speaker-attributed transcript. Owned by Meeting.
// -----------------------------------------------------------------------------
MERGE (obj004:BusinessEntity {id: 'OBJ-004'})
SET obj004.name        = 'Transcript',
    obj004.description = 'Persisted verbatim transcript output from the ASR + diarization pipeline. Contains the full speaker-attributed text and summary statistics. Individual segments are stored as part of the transcript (e.g., as a JSON/structured field) rather than as separate graph entities at MVP scope.',
    obj004.stereotype  = 'document',
    obj004.status      = 'draft',
    obj004.created     = date('2026-05-17'),
    obj004.updated     = date('2026-05-17');

MERGE (a41:EntityAttribute {id: 'OBJ-004-A01'})
SET a41.name = 'id',              a41.type = 'UUID',     a41.required = true,  a41.description = 'Unique transcript identifier';
MERGE (a42:EntityAttribute {id: 'OBJ-004-A02'})
SET a42.name = 'meeting_id',      a42.type = 'UUID',     a42.required = true,  a42.description = 'Foreign key to owning Meeting (OBJ-001)';
MERGE (a43:EntityAttribute {id: 'OBJ-004-A03'})
SET a43.name = 'full_text',       a43.type = 'Text',     a43.required = true,  a43.description = 'Full verbatim transcript in Markdown or structured text; includes speaker labels and timestamps per segment';
MERGE (a44:EntityAttribute {id: 'OBJ-004-A04'})
SET a44.name = 'segments_count',  a44.type = 'Integer',  a44.required = true,  a44.description = 'Total number of speaker-attributed segments in the transcript';
MERGE (a45:EntityAttribute {id: 'OBJ-004-A05'})
SET a45.name = 'speakers_count',  a45.type = 'Integer',  a45.required = true,  a45.description = 'Number of distinct speakers detected by the diarization engine';
MERGE (a46:EntityAttribute {id: 'OBJ-004-A06'})
SET a46.name = 'language',        a46.type = 'String',   a46.required = true,  a46.description = 'Detected or confirmed language code of the transcript (e.g., ru, en)';
MERGE (a47:EntityAttribute {id: 'OBJ-004-A07'})
SET a47.name = 'created_at',      a47.type = 'DateTime', a47.required = true,  a47.description = 'Timestamp when the transcript was first persisted';

MERGE (obj004:BusinessEntity {id: 'OBJ-004'})
MERGE (a41:EntityAttribute {id: 'OBJ-004-A01'}) MERGE (obj004)-[:HAS_ATTRIBUTE]->(a41)
MERGE (a42:EntityAttribute {id: 'OBJ-004-A02'}) MERGE (obj004)-[:HAS_ATTRIBUTE]->(a42)
MERGE (a43:EntityAttribute {id: 'OBJ-004-A03'}) MERGE (obj004)-[:HAS_ATTRIBUTE]->(a43)
MERGE (a44:EntityAttribute {id: 'OBJ-004-A04'}) MERGE (obj004)-[:HAS_ATTRIBUTE]->(a44)
MERGE (a45:EntityAttribute {id: 'OBJ-004-A05'}) MERGE (obj004)-[:HAS_ATTRIBUTE]->(a45)
MERGE (a46:EntityAttribute {id: 'OBJ-004-A06'}) MERGE (obj004)-[:HAS_ATTRIBUTE]->(a46)
MERGE (a47:EntityAttribute {id: 'OBJ-004-A07'}) MERGE (obj004)-[:HAS_ATTRIBUTE]->(a47);

// No independent lifecycle — status is tracked via Meeting and TranscriptionJob.

// -----------------------------------------------------------------------------
// OBJ-005 — ProtocolGenerationJob
// Async job for LLM protocol generation. Owned by Meeting.
// -----------------------------------------------------------------------------
MERGE (obj005:BusinessEntity {id: 'OBJ-005'})
SET obj005.name        = 'ProtocolGenerationJob',
    obj005.description = 'Async job record tracking the LLM-based protocol generation pipeline for a given transcript. Created automatically when the transcription job completes (BP-004 trigger). Tracks prompt template version used, timing, and failure details.',
    obj005.stereotype  = 'job',
    obj005.status      = 'draft',
    obj005.created     = date('2026-05-17'),
    obj005.updated     = date('2026-05-17');

MERGE (a51:EntityAttribute {id: 'OBJ-005-A01'})
SET a51.name = 'id',                      a51.type = 'UUID',     a51.required = true,  a51.description = 'Unique job identifier';
MERGE (a52:EntityAttribute {id: 'OBJ-005-A02'})
SET a52.name = 'meeting_id',              a52.type = 'UUID',     a52.required = true,  a52.description = 'Foreign key to owning Meeting (OBJ-001)';
MERGE (a53:EntityAttribute {id: 'OBJ-005-A03'})
SET a53.name = 'transcript_id',           a53.type = 'UUID',     a53.required = true,  a53.description = 'Foreign key to the Transcript being summarized (OBJ-004)';
MERGE (a54:EntityAttribute {id: 'OBJ-005-A04'})
SET a54.name = 'status',                  a54.type = 'Enum',     a54.required = true,  a54.description = 'Job lifecycle status (see states OBJ-005-ST01..ST04)';
MERGE (a55:EntityAttribute {id: 'OBJ-005-A05'})
SET a55.name = 'error_reason',            a55.type = 'String',   a55.required = false, a55.description = 'Human-readable error description when status = failed';
MERGE (a56:EntityAttribute {id: 'OBJ-005-A06'})
SET a56.name = 'prompt_template_version', a56.type = 'String',   a56.required = true,  a56.description = 'Version identifier of the prompt template used for this generation run; enables reproducibility audits';
MERGE (a57:EntityAttribute {id: 'OBJ-005-A07'})
SET a57.name = 'started_at',              a57.type = 'DateTime', a57.required = false, a57.description = 'Timestamp when the worker picked up the job';
MERGE (a58:EntityAttribute {id: 'OBJ-005-A08'})
SET a58.name = 'completed_at',            a58.type = 'DateTime', a58.required = false, a58.description = 'Timestamp when the job reached a terminal state (completed or failed)';

MERGE (obj005:BusinessEntity {id: 'OBJ-005'})
MERGE (a51:EntityAttribute {id: 'OBJ-005-A01'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a51)
MERGE (a52:EntityAttribute {id: 'OBJ-005-A02'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a52)
MERGE (a53:EntityAttribute {id: 'OBJ-005-A03'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a53)
MERGE (a54:EntityAttribute {id: 'OBJ-005-A04'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a54)
MERGE (a55:EntityAttribute {id: 'OBJ-005-A05'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a55)
MERGE (a56:EntityAttribute {id: 'OBJ-005-A06'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a56)
MERGE (a57:EntityAttribute {id: 'OBJ-005-A07'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a57)
MERGE (a58:EntityAttribute {id: 'OBJ-005-A08'}) MERGE (obj005)-[:HAS_ATTRIBUTE]->(a58);

// Lifecycle states
MERGE (st51:EntityState {id: 'OBJ-005-ST01'}) SET st51.name = 'queued',      st51.description = 'Job has been created and is waiting for a worker';
MERGE (st52:EntityState {id: 'OBJ-005-ST02'}) SET st52.name = 'in_progress', st52.description = 'Worker is executing the LLM request and awaiting response';
MERGE (st53:EntityState {id: 'OBJ-005-ST03'}) SET st53.name = 'completed',   st53.description = 'Protocol produced and persisted successfully';
MERGE (st54:EntityState {id: 'OBJ-005-ST04'}) SET st54.name = 'failed',      st54.description = 'Job terminated with a non-recoverable error (e.g., LLM timeout, token limit exceeded)';

MERGE (obj005:BusinessEntity {id: 'OBJ-005'})
MERGE (st51:EntityState {id: 'OBJ-005-ST01'}) MERGE (obj005)-[:HAS_STATE]->(st51)
MERGE (st52:EntityState {id: 'OBJ-005-ST02'}) MERGE (obj005)-[:HAS_STATE]->(st52)
MERGE (st53:EntityState {id: 'OBJ-005-ST03'}) MERGE (obj005)-[:HAS_STATE]->(st53)
MERGE (st54:EntityState {id: 'OBJ-005-ST04'}) MERGE (obj005)-[:HAS_STATE]->(st54);

MERGE (st51:EntityState {id: 'OBJ-005-ST01'}) MERGE (st52:EntityState {id: 'OBJ-005-ST02'}) MERGE (st51)-[:TRANSITIONS_TO]->(st52);
MERGE (st52:EntityState {id: 'OBJ-005-ST02'}) MERGE (st53:EntityState {id: 'OBJ-005-ST03'}) MERGE (st52)-[:TRANSITIONS_TO]->(st53);
MERGE (st52:EntityState {id: 'OBJ-005-ST02'}) MERGE (st54:EntityState {id: 'OBJ-005-ST04'}) MERGE (st52)-[:TRANSITIONS_TO]->(st54);

// -----------------------------------------------------------------------------
// OBJ-006 — Protocol
// Meeting protocol Markdown document. Owned by Meeting.
// -----------------------------------------------------------------------------
MERGE (obj006:BusinessEntity {id: 'OBJ-006'})
SET obj006.name        = 'Protocol',
    obj006.description = 'Persisted meeting protocol produced by the LLM generation pipeline and optionally refined by the user. Stored as Markdown. Contains structured sections: participants, agenda topics, decisions, and action items with assignees and deadlines. Version-incremented on each save.',
    obj006.stereotype  = 'document',
    obj006.status      = 'draft',
    obj006.created     = date('2026-05-17'),
    obj006.updated     = date('2026-05-17');

MERGE (a61:EntityAttribute {id: 'OBJ-006-A01'})
SET a61.name = 'id',               a61.type = 'UUID',     a61.required = true,  a61.description = 'Unique protocol identifier';
MERGE (a62:EntityAttribute {id: 'OBJ-006-A02'})
SET a62.name = 'meeting_id',       a62.type = 'UUID',     a62.required = true,  a62.description = 'Foreign key to owning Meeting (OBJ-001)';
MERGE (a63:EntityAttribute {id: 'OBJ-006-A03'})
SET a63.name = 'markdown_content', a63.type = 'Text',     a63.required = true,  a63.description = 'Full protocol text in Markdown; the authoritative editable representation';
MERGE (a64:EntityAttribute {id: 'OBJ-006-A04'})
SET a64.name = 'generated_at',     a64.type = 'DateTime', a64.required = true,  a64.description = 'Timestamp when the protocol was first produced by the LLM pipeline';
MERGE (a65:EntityAttribute {id: 'OBJ-006-A05'})
SET a65.name = 'last_edited_at',   a65.type = 'DateTime', a65.required = false, a65.description = 'Timestamp of the most recent manual save in BP-005; null if never edited';
MERGE (a66:EntityAttribute {id: 'OBJ-006-A06'})
SET a66.name = 'edit_count',       a66.type = 'Integer',  a66.required = true,  a66.description = 'Number of times the protocol has been manually saved; starts at 0';
MERGE (a67:EntityAttribute {id: 'OBJ-006-A07'})
SET a67.name = 'version',          a67.type = 'Integer',  a67.required = true,  a67.description = 'Monotonically incrementing version number; incremented on each save in BP-005';

MERGE (obj006:BusinessEntity {id: 'OBJ-006'})
MERGE (a61:EntityAttribute {id: 'OBJ-006-A01'}) MERGE (obj006)-[:HAS_ATTRIBUTE]->(a61)
MERGE (a62:EntityAttribute {id: 'OBJ-006-A02'}) MERGE (obj006)-[:HAS_ATTRIBUTE]->(a62)
MERGE (a63:EntityAttribute {id: 'OBJ-006-A03'}) MERGE (obj006)-[:HAS_ATTRIBUTE]->(a63)
MERGE (a64:EntityAttribute {id: 'OBJ-006-A04'}) MERGE (obj006)-[:HAS_ATTRIBUTE]->(a64)
MERGE (a65:EntityAttribute {id: 'OBJ-006-A05'}) MERGE (obj006)-[:HAS_ATTRIBUTE]->(a65)
MERGE (a66:EntityAttribute {id: 'OBJ-006-A06'}) MERGE (obj006)-[:HAS_ATTRIBUTE]->(a66)
MERGE (a67:EntityAttribute {id: 'OBJ-006-A07'}) MERGE (obj006)-[:HAS_ATTRIBUTE]->(a67);

// No independent lifecycle — status tracked via Meeting.

// =============================================================================
// ENTITY-TO-ENTITY OWNERSHIP (REFERENCES)
// =============================================================================

// Meeting owns all downstream entities
MERGE (obj001:BusinessEntity {id: 'OBJ-001'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (obj001)-[:REFERENCES]->(obj002)
MERGE (obj003:BusinessEntity {id: 'OBJ-003'}) MERGE (obj001)-[:REFERENCES]->(obj003)
MERGE (obj004:BusinessEntity {id: 'OBJ-004'}) MERGE (obj001)-[:REFERENCES]->(obj004)
MERGE (obj005:BusinessEntity {id: 'OBJ-005'}) MERGE (obj001)-[:REFERENCES]->(obj005)
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (obj001)-[:REFERENCES]->(obj006);

// TranscriptionJob references Recording
MERGE (obj003:BusinessEntity {id: 'OBJ-003'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'})
MERGE (obj003)-[:REFERENCES]->(obj002);

// ProtocolGenerationJob references Transcript
MERGE (obj005:BusinessEntity {id: 'OBJ-005'})
MERGE (obj004:BusinessEntity {id: 'OBJ-004'})
MERGE (obj005)-[:REFERENCES]->(obj004);

// =============================================================================
// PROCESS-ENTITY MATRIX (PRODUCES / CONSUMES)
// =============================================================================

// BP-001 Upload Meeting Video
MERGE (bp001:BusinessProcess {id: 'BP-001'})
MERGE (obj001:BusinessEntity {id: 'OBJ-001'}) MERGE (bp001)-[:PRODUCES]->(obj001)
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (bp001)-[:PRODUCES]->(obj002)
MERGE (obj003:BusinessEntity {id: 'OBJ-003'}) MERGE (bp001)-[:PRODUCES]->(obj003);

// BP-002 Transcribe Audio
MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (bp002)-[:CONSUMES]->(obj002)
MERGE (obj003:BusinessEntity {id: 'OBJ-003'}) MERGE (bp002)-[:CONSUMES]->(obj003)
MERGE (obj004:BusinessEntity {id: 'OBJ-004'}) MERGE (bp002)-[:PRODUCES]->(obj004)
MERGE (obj005:BusinessEntity {id: 'OBJ-005'}) MERGE (bp002)-[:PRODUCES]->(obj005);

// BP-003 Download / Retrieve Transcript
MERGE (bp003:BusinessProcess {id: 'BP-003'})
MERGE (obj004:BusinessEntity {id: 'OBJ-004'}) MERGE (bp003)-[:CONSUMES]->(obj004);

// BP-004 Generate Meeting Protocol
MERGE (bp004:BusinessProcess {id: 'BP-004'})
MERGE (obj004:BusinessEntity {id: 'OBJ-004'}) MERGE (bp004)-[:CONSUMES]->(obj004)
MERGE (obj005:BusinessEntity {id: 'OBJ-005'}) MERGE (bp004)-[:CONSUMES]->(obj005)
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (bp004)-[:PRODUCES]->(obj006);

// BP-005 Review and Edit Protocol
MERGE (bp005:BusinessProcess {id: 'BP-005'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (bp005)-[:CONSUMES]->(obj006)
MERGE (obj006b:BusinessEntity {id: 'OBJ-006'}) MERGE (bp005)-[:PRODUCES]->(obj006b);

// BP-006 Export Protocol to PDF
MERGE (bp006:BusinessProcess {id: 'BP-006'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (bp006)-[:CONSUMES]->(obj006);
// BP-006 produces no persistent entity — output is a transient file download delivered to the user.
