// =============================================================================
// BA Glossary Seed — Transcrib
// Generated by: nacl-ba-glossary full
// Date: 2026-05-17
// =============================================================================
// Idempotent: all writes use MERGE on {id}. Safe to re-run.
// Total terms: 22
// =============================================================================

// =============================================================================
// GLOSSARY TERMS — Core Domain (Entities & Roles)
// =============================================================================

// -----------------------------------------------------------------------------
// GLO-001 — Meeting
// -----------------------------------------------------------------------------
MERGE (glo001:GlossaryTerm {id: 'GLO-001'})
SET glo001.name            = 'Meeting',
    glo001.definition      = 'A single business meeting whose recording is uploaded into the system for processing. The root object that owns the resulting recording, transcript, and protocol throughout its lifecycle.',
    glo001.aliases         = ['Встреча', 'Session'],
    glo001.context         = 'Used throughout all processes (BP-001..BP-006); the top-level aggregate (OBJ-001).',
    glo001.status          = 'draft',
    glo001.created         = date('2026-05-17'),
    glo001.updated         = date('2026-05-17');

MERGE (glo001:GlossaryTerm {id: 'GLO-001'})
MERGE (obj001:BusinessEntity {id: 'OBJ-001'})
MERGE (glo001)-[:DEFINES_TERM]->(obj001);

// -----------------------------------------------------------------------------
// GLO-002 — Recording
// -----------------------------------------------------------------------------
MERGE (glo002:GlossaryTerm {id: 'GLO-002'})
SET glo002.name            = 'Recording',
    glo002.definition      = 'The video file uploaded by the Author that captures the meeting. The physical file is stored in object storage; the system tracks its metadata (filename, size, duration, storage path) as the Recording entity.',
    glo002.aliases         = ['Видеозапись', 'Запись', 'Video File'],
    glo002.context         = 'Created in BP-001 (Upload); consumed in BP-002 (Transcription). Corresponds to OBJ-002.',
    glo002.status          = 'draft',
    glo002.created         = date('2026-05-17'),
    glo002.updated         = date('2026-05-17');

MERGE (glo002:GlossaryTerm {id: 'GLO-002'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'})
MERGE (glo002)-[:DEFINES_TERM]->(obj002);

// -----------------------------------------------------------------------------
// GLO-003 — Transcript
// -----------------------------------------------------------------------------
MERGE (glo003:GlossaryTerm {id: 'GLO-003'})
SET glo003.name            = 'Transcript',
    glo003.definition      = 'The verbatim, speaker-attributed text output of the transcription pipeline. Contains the full spoken content of the meeting with speaker labels and timestamps per segment. Sometimes called a "verbatim transcript" to distinguish it from a summarized protocol.',
    glo003.aliases         = ['Транскрипт', 'Пословная транскрибация', 'Verbatim Transcript'],
    glo003.context         = 'Produced by BP-002 (Transcription); consumed by BP-003 (Retrieve) and BP-004 (Protocol Generation). Corresponds to OBJ-004.',
    glo003.status          = 'draft',
    glo003.created         = date('2026-05-17'),
    glo003.updated         = date('2026-05-17');

MERGE (glo003:GlossaryTerm {id: 'GLO-003'})
MERGE (obj004:BusinessEntity {id: 'OBJ-004'})
MERGE (glo003)-[:DEFINES_TERM]->(obj004);

// -----------------------------------------------------------------------------
// GLO-004 — Speaker Diarization
// -----------------------------------------------------------------------------
MERGE (glo004:GlossaryTerm {id: 'GLO-004'})
SET glo004.name            = 'Speaker Diarization',
    glo004.definition      = 'The automated process of partitioning an audio stream into segments and labeling each segment with a speaker identity (e.g., Speaker 1, Speaker 2). Diarization answers the question "who spoke when" and is a required step of the transcription pipeline.',
    glo004.aliases         = ['Диаризация спикеров', 'Diarization'],
    glo004.context         = 'Performed inside BP-002 (Transcription) by the ASR/Diarization Engine (EXT-01). Output feeds into speaker-attributed transcript segments.',
    glo004.status          = 'draft',
    glo004.created         = date('2026-05-17'),
    glo004.updated         = date('2026-05-17');

MERGE (glo004:GlossaryTerm {id: 'GLO-004'})
MERGE (ext01:ExternalEntity {id: 'EXT-01'})
MERGE (glo004)-[:DEFINES_TERM]->(ext01);

// -----------------------------------------------------------------------------
// GLO-005 — Speaker Segment
// -----------------------------------------------------------------------------
MERGE (glo005:GlossaryTerm {id: 'GLO-005'})
SET glo005.name            = 'Speaker Segment',
    glo005.definition      = 'A contiguous block of speech attributed to a single speaker, with a start timestamp, end timestamp, speaker label, and verbatim text. Multiple segments together form the full Transcript.',
    glo005.aliases         = ['Сегмент транскрипта', 'Transcript Segment'],
    glo005.context         = 'Produced by the diarization step inside BP-002; stored as structured content within OBJ-004 (Transcript) at MVP scope.',
    glo005.status          = 'draft',
    glo005.created         = date('2026-05-17'),
    glo005.updated         = date('2026-05-17');

// No direct DEFINES_TERM pointer — segment is embedded in OBJ-004, not a top-level graph node at MVP.

// -----------------------------------------------------------------------------
// GLO-006 — Meeting Protocol
// -----------------------------------------------------------------------------
MERGE (glo006:GlossaryTerm {id: 'GLO-006'})
SET glo006.name            = 'Meeting Protocol',
    glo006.definition      = 'A structured summary document produced from the transcript by the LLM generation pipeline. Contains sections for meeting participants, discussion topics, decisions made, and action items with assignees and deadlines. Stored in Markdown and exportable to PDF.',
    glo006.aliases         = ['Протокол встречи', 'Protocol', 'Minutes'],
    glo006.context         = 'Produced by BP-004; edited in BP-005; exported in BP-006. Corresponds to OBJ-006.',
    glo006.status          = 'draft',
    glo006.created         = date('2026-05-17'),
    glo006.updated         = date('2026-05-17');

MERGE (glo006:GlossaryTerm {id: 'GLO-006'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'})
MERGE (glo006)-[:DEFINES_TERM]->(obj006);

// GLO-007 is "Protocol" — canonical synonym of GLO-006 (Meeting Protocol)
MERGE (glo007:GlossaryTerm {id: 'GLO-007'})
SET glo007.name            = 'Protocol',
    glo007.definition      = 'Short-form alias for Meeting Protocol (GLO-006). Used interchangeably in the codebase and UI labels.',
    glo007.aliases         = ['Протокол'],
    glo007.context         = 'Appears in entity names (OBJ-006), process names (BP-004, BP-005, BP-006), and UI labels.',
    glo007.status          = 'draft',
    glo007.created         = date('2026-05-17'),
    glo007.updated         = date('2026-05-17');

MERGE (glo007:GlossaryTerm {id: 'GLO-007'})
MERGE (glo006:GlossaryTerm {id: 'GLO-006'})
MERGE (glo007)-[:SYNONYM_OF]->(glo006);

// -----------------------------------------------------------------------------
// GLO-008 — Action Item
// -----------------------------------------------------------------------------
MERGE (glo008:GlossaryTerm {id: 'GLO-008'})
SET glo008.name            = 'Action Item',
    glo008.definition      = 'A task agreed upon during the meeting, assigned to a named person with a deadline. Action items are extracted by the LLM from the transcript and appear as a dedicated section of the protocol.',
    glo008.aliases         = ['Поручение', 'Задача', 'Task'],
    glo008.context         = 'Captured as a section within OBJ-006 (Protocol); extracted during BP-004 (Protocol Generation).',
    glo008.status          = 'draft',
    glo008.created         = date('2026-05-17'),
    glo008.updated         = date('2026-05-17');

// No separate graph node — embedded in Protocol document.

// -----------------------------------------------------------------------------
// GLO-009 — Decision
// -----------------------------------------------------------------------------
MERGE (glo009:GlossaryTerm {id: 'GLO-009'})
SET glo009.name            = 'Decision',
    glo009.definition      = 'A conclusion or resolution reached during the meeting that is explicitly recorded in the protocol. Decisions are distinct from action items in that they represent outcomes rather than future tasks.',
    glo009.aliases         = ['Решение'],
    glo009.context         = 'Captured as a section within OBJ-006 (Protocol); extracted during BP-004 (Protocol Generation).',
    glo009.status          = 'draft',
    glo009.created         = date('2026-05-17'),
    glo009.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// GLO-010 — Discussion Topic
// -----------------------------------------------------------------------------
MERGE (glo010:GlossaryTerm {id: 'GLO-010'})
SET glo010.name            = 'Discussion Topic',
    glo010.definition      = 'A distinct agenda point or subject discussed during the meeting. The LLM groups related transcript content under topics, which become named sections within the protocol.',
    glo010.aliases         = ['Тема обсуждения', 'Вопрос', 'Agenda Item'],
    glo010.context         = 'Captured as a section within OBJ-006 (Protocol); extracted during BP-004 (Protocol Generation).',
    glo010.status          = 'draft',
    glo010.created         = date('2026-05-17'),
    glo010.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// GLO-011 — Participant
// -----------------------------------------------------------------------------
MERGE (glo011:GlossaryTerm {id: 'GLO-011'})
SET glo011.name            = 'Participant',
    glo011.definition      = 'A person who took part in the meeting. Participants are identified from the transcript by the diarization engine (as speaker labels) and optionally mapped to real names. The participant list appears as a dedicated section of the protocol.',
    glo011.aliases         = ['Участник', 'Attendee', 'Speaker'],
    glo011.context         = 'Derived from speaker segments in OBJ-004 (Transcript); surfaced in OBJ-006 (Protocol).',
    glo011.status          = 'draft',
    glo011.created         = date('2026-05-17'),
    glo011.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// GLO-012 — Author (Role)
// -----------------------------------------------------------------------------
MERGE (glo012:GlossaryTerm {id: 'GLO-012'})
SET glo012.name            = 'Author',
    glo012.definition      = 'The business role representing the person who uploaded the meeting recording and owns all derived artifacts (transcript and protocol). The primary — and at MVP the only — active human role in the system.',
    glo012.aliases         = ['Автор', 'Uploader'],
    glo012.context         = 'Defined as ROL-01; performs BP-001, BP-003, BP-005, BP-006.',
    glo012.status          = 'draft',
    glo012.created         = date('2026-05-17'),
    glo012.updated         = date('2026-05-17');

MERGE (glo012:GlossaryTerm {id: 'GLO-012'})
MERGE (rol01:BusinessRole {id: 'ROL-01'})
MERGE (glo012)-[:DEFINES_TERM]->(rol01);

// -----------------------------------------------------------------------------
// GLO-013 — Reviewer (Role)
// -----------------------------------------------------------------------------
MERGE (glo013:GlossaryTerm {id: 'GLO-013'})
SET glo013.name            = 'Reviewer',
    glo013.definition      = 'A business role representing a meeting participant who reads and validates the generated protocol. At MVP there is no technical distinction from Author; this role is modeled as an assumption for future access-control design.',
    glo013.aliases         = ['Проверяющий', 'Читатель'],
    glo013.context         = 'Defined as ROL-02; assumption — no distinct system behavior at MVP.',
    glo013.assumption_note = 'No authentication or sharing mechanism exists at MVP. This role is forward-looking only.',
    glo013.status          = 'draft',
    glo013.created         = date('2026-05-17'),
    glo013.updated         = date('2026-05-17');

MERGE (glo013:GlossaryTerm {id: 'GLO-013'})
MERGE (rol02:BusinessRole {id: 'ROL-02'})
MERGE (glo013)-[:DEFINES_TERM]->(rol02);

// =============================================================================
// GLOSSARY TERMS — Pipeline / Technical (business-facing)
// =============================================================================

// -----------------------------------------------------------------------------
// GLO-014 — Transcription Pipeline
// -----------------------------------------------------------------------------
MERGE (glo014:GlossaryTerm {id: 'GLO-014'})
SET glo014.name            = 'Transcription Pipeline',
    glo014.definition      = 'The end-to-end automated sequence of steps that transforms an uploaded video recording into a verbatim speaker-attributed transcript. Encompasses audio extraction, ASR, and speaker diarization.',
    glo014.aliases         = ['Пайплайн транскрибации', 'Transcription Flow'],
    glo014.context         = 'Corresponds to BP-002 (Transcribe Audio) and its constituent workflow steps.',
    glo014.status          = 'draft',
    glo014.created         = date('2026-05-17'),
    glo014.updated         = date('2026-05-17');

MERGE (glo014:GlossaryTerm {id: 'GLO-014'})
MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (glo014)-[:DEFINES_TERM]->(bp002);

// -----------------------------------------------------------------------------
// GLO-015 — Protocol Lifecycle
// -----------------------------------------------------------------------------
MERGE (glo015:GlossaryTerm {id: 'GLO-015'})
SET glo015.name            = 'Protocol Lifecycle',
    glo015.definition      = 'The ordered sequence of states a Meeting Protocol passes through from generation to final export: generated → edited (zero or more times) → exported. Tracks how the document evolves after LLM creation.',
    glo015.aliases         = ['Жизненный цикл протокола'],
    glo015.context         = 'Spans BP-004 (generation), BP-005 (editing), BP-006 (export); states tracked via OBJ-006 and Meeting status OBJ-001.',
    glo015.status          = 'draft',
    glo015.created         = date('2026-05-17'),
    glo015.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// GLO-016 — ASR (Automatic Speech Recognition)
// -----------------------------------------------------------------------------
MERGE (glo016:GlossaryTerm {id: 'GLO-016'})
SET glo016.name            = 'ASR',
    glo016.definition      = 'Automatic Speech Recognition — the technology that converts audio speech into written text. In Transcrib, ASR is performed by an external engine (EXT-01) that also handles speaker diarization.',
    glo016.aliases         = ['Automatic Speech Recognition', 'Распознавание речи', 'Speech-to-Text', 'STT'],
    glo016.context         = 'Invoked inside BP-002 (Transcription); vendor/model is TBD.',
    glo016.status          = 'draft',
    glo016.created         = date('2026-05-17'),
    glo016.updated         = date('2026-05-17');

MERGE (glo016:GlossaryTerm {id: 'GLO-016'})
MERGE (ext01:ExternalEntity {id: 'EXT-01'})
MERGE (glo016)-[:DEFINES_TERM]->(ext01);

// -----------------------------------------------------------------------------
// GLO-017 — LLM (Large Language Model)
// -----------------------------------------------------------------------------
MERGE (glo017:GlossaryTerm {id: 'GLO-017'})
SET glo017.name            = 'LLM',
    glo017.definition      = 'Large Language Model — an AI model used to summarize and structure the verbatim transcript into a formatted meeting protocol. The LLM receives a prompt containing the transcript and a template, and returns structured Markdown.',
    glo017.aliases         = ['Large Language Model', 'Большая языковая модель', 'Language Model'],
    glo017.context         = 'Invoked inside BP-004 (Protocol Generation) via EXT-02; specific service is TBD.',
    glo017.status          = 'draft',
    glo017.created         = date('2026-05-17'),
    glo017.updated         = date('2026-05-17');

MERGE (glo017:GlossaryTerm {id: 'GLO-017'})
MERGE (ext02:ExternalEntity {id: 'EXT-02'})
MERGE (glo017)-[:DEFINES_TERM]->(ext02);

// -----------------------------------------------------------------------------
// GLO-018 — Async Job
// -----------------------------------------------------------------------------
MERGE (glo018:GlossaryTerm {id: 'GLO-018'})
SET glo018.name            = 'Async Job',
    glo018.definition      = 'An asynchronous background task that performs a long-running operation (transcription or protocol generation) outside the synchronous request-response cycle. The user polls or receives a notification when the job completes.',
    glo018.aliases         = ['Асинхронная задача', 'Background Job'],
    glo018.context         = 'Materialized as OBJ-003 (TranscriptionJob) and OBJ-005 (ProtocolGenerationJob).',
    glo018.status          = 'draft',
    glo018.created         = date('2026-05-17'),
    glo018.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// GLO-019 — TranscriptionJob
// -----------------------------------------------------------------------------
MERGE (glo019:GlossaryTerm {id: 'GLO-019'})
SET glo019.name            = 'TranscriptionJob',
    glo019.definition      = 'The specific async job record that tracks ASR and diarization pipeline execution for a single recording. Transitions through queued → in_progress → completed | failed, and is the primary means of surfacing transcription progress and errors to the system.',
    glo019.aliases         = ['Задача транскрибации'],
    glo019.context         = 'Created in BP-001; executed in BP-002. Corresponds to OBJ-003.',
    glo019.status          = 'draft',
    glo019.created         = date('2026-05-17'),
    glo019.updated         = date('2026-05-17');

MERGE (glo019:GlossaryTerm {id: 'GLO-019'})
MERGE (obj003:BusinessEntity {id: 'OBJ-003'})
MERGE (glo019)-[:DEFINES_TERM]->(obj003);

// -----------------------------------------------------------------------------
// GLO-020 — ProtocolGenerationJob
// -----------------------------------------------------------------------------
MERGE (glo020:GlossaryTerm {id: 'GLO-020'})
SET glo020.name            = 'ProtocolGenerationJob',
    glo020.definition      = 'The specific async job record that tracks LLM-based protocol generation for a single transcript. Created automatically when the TranscriptionJob completes; tracks prompt template version, timing, and failure details.',
    glo020.aliases         = ['Задача генерации протокола'],
    glo020.context         = 'Triggered at end of BP-002; executed in BP-004. Corresponds to OBJ-005.',
    glo020.status          = 'draft',
    glo020.created         = date('2026-05-17'),
    glo020.updated         = date('2026-05-17');

MERGE (glo020:GlossaryTerm {id: 'GLO-020'})
MERGE (obj005:BusinessEntity {id: 'OBJ-005'})
MERGE (glo020)-[:DEFINES_TERM]->(obj005);

// -----------------------------------------------------------------------------
// GLO-021 — Object Storage
// -----------------------------------------------------------------------------
MERGE (glo021:GlossaryTerm {id: 'GLO-021'})
SET glo021.name            = 'Object Storage',
    glo021.definition      = 'A remote binary storage service used to persist large video files uploaded by the user. The system stores the file in object storage and records only the storage path reference in the Recording entity.',
    glo021.aliases         = ['Объектное хранилище', 'Blob Storage', 'File Storage'],
    glo021.context         = 'Corresponds to EXT-04; used in BP-001 (Upload) and BP-002 (Transcription); specific service is TBD.',
    glo021.status          = 'draft',
    glo021.created         = date('2026-05-17'),
    glo021.updated         = date('2026-05-17');

MERGE (glo021:GlossaryTerm {id: 'GLO-021'})
MERGE (ext04:ExternalEntity {id: 'EXT-04'})
MERGE (glo021)-[:DEFINES_TERM]->(ext04);

// -----------------------------------------------------------------------------
// GLO-022 — Prompt Template
// -----------------------------------------------------------------------------
MERGE (glo022:GlossaryTerm {id: 'GLO-022'})
SET glo022.name            = 'Prompt Template',
    glo022.definition      = 'A versioned template that defines the structure and instructions given to the LLM when generating a meeting protocol from a transcript. The template controls which sections (participants, topics, decisions, action items) the LLM must produce and in what format.',
    glo022.aliases         = ['Шаблон промпта', 'LLM Prompt'],
    glo022.context         = 'Used in BP-004 (Protocol Generation); version is recorded in OBJ-005 (ProtocolGenerationJob) for audit.',
    glo022.assumption_note = 'Template format and versioning mechanism are TBD at MVP; the term is recorded to ensure traceability of generation reproducibility.',
    glo022.status          = 'draft',
    glo022.created         = date('2026-05-17'),
    glo022.updated         = date('2026-05-17');

// =============================================================================
// GLOSSARY TERMS — Operational Concepts
// =============================================================================

// -----------------------------------------------------------------------------
// GLO-023 — Markdown
// -----------------------------------------------------------------------------
MERGE (glo023:GlossaryTerm {id: 'GLO-023'})
SET glo023.name            = 'Markdown',
    glo023.definition      = 'A lightweight text markup language used as the internal storage format for meeting protocols. The user edits the protocol as Markdown in the built-in editor; Markdown is also the source format for PDF export.',
    glo023.aliases         = ['Маркдаун'],
    glo023.context         = 'Stored in OBJ-006.markdown_content; edited in BP-005; exported in BP-006.',
    glo023.status          = 'draft',
    glo023.created         = date('2026-05-17'),
    glo023.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// GLO-024 — PDF Export
// -----------------------------------------------------------------------------
MERGE (glo024:GlossaryTerm {id: 'GLO-024'})
SET glo024.name            = 'PDF Export',
    glo024.definition      = 'The on-demand conversion of a Markdown protocol document to a PDF file delivered to the user as a browser download. The PDF is a transient artifact — it is not persisted in the system after delivery.',
    glo024.aliases         = ['Экспорт в PDF', 'Export to PDF'],
    glo024.context         = 'Performed in BP-006 (Export Protocol to PDF); triggered by the Author.',
    glo024.status          = 'draft',
    glo024.created         = date('2026-05-17'),
    glo024.updated         = date('2026-05-17');

MERGE (glo024:GlossaryTerm {id: 'GLO-024'})
MERGE (bp006:BusinessProcess {id: 'BP-006'})
MERGE (glo024)-[:DEFINES_TERM]->(bp006);

// -----------------------------------------------------------------------------
// GLO-025 — Upload
// -----------------------------------------------------------------------------
MERGE (glo025:GlossaryTerm {id: 'GLO-025'})
SET glo025.name            = 'Upload',
    glo025.definition      = 'The user action of submitting a video file to the system via the web interface. Upload initiates the meeting record creation and queues the transcription pipeline. Files up to 300–500 MB must be supported.',
    glo025.aliases         = ['Загрузка', 'File Upload'],
    glo025.context         = 'The first user action; corresponds to BP-001 (Upload Meeting Video).',
    glo025.status          = 'draft',
    glo025.created         = date('2026-05-17'),
    glo025.updated         = date('2026-05-17');

MERGE (glo025:GlossaryTerm {id: 'GLO-025'})
MERGE (bp001:BusinessProcess {id: 'BP-001'})
MERGE (glo025)-[:DEFINES_TERM]->(bp001);

// -----------------------------------------------------------------------------
// GLO-026 — Language Hint
// -----------------------------------------------------------------------------
MERGE (glo026:GlossaryTerm {id: 'GLO-026'})
SET glo026.name            = 'Language Hint',
    glo026.definition      = 'An optional user-supplied indication of the primary spoken language in the recording (e.g., Russian, English, or auto-detect). The ASR engine uses this hint to improve transcription accuracy.',
    glo026.aliases         = ['Подсказка языка', 'Source Language', 'Language Setting'],
    glo026.context         = 'Stored as Meeting.language (OBJ-001-A03); supplied during BP-001 (Upload); passed to the ASR engine in BP-002.',
    glo026.assumption_note = 'The set of supported languages and whether auto-detection is accurate are TBD pending ASR vendor selection.',
    glo026.status          = 'draft',
    glo026.created         = date('2026-05-17'),
    glo026.updated         = date('2026-05-17');

MERGE (glo026:GlossaryTerm {id: 'GLO-026'})
MERGE (obj001:BusinessEntity {id: 'OBJ-001'})
MERGE (glo026)-[:DEFINES_TERM]->(obj001);

// =============================================================================
// END OF SEED
// =============================================================================
