// =============================================================================
// BA Glossary Seed — Transcrib
// Generated by: nacl-ba-glossary (WP-SPEC-01 revision 2026-10-09)
// =============================================================================
// Idempotent: all writes use MERGE on {id}. Safe to re-run.
// ENCODING: UTF-8. Load with: LANG=C.UTF-8 cypher-shell --encoding utf-8 -f <file>
//   (a load without UTF-8 turned Russian aliases into '?' in 2026-05; see WP-SPEC-01)
// Total terms: 46 (GLO-007 merged into GLO-006, node removed)
// Name rule: `name` = English term (code-facing identifier); `name_ru` = the Russian
// product term; aliases[0] is the Russian primary alias. The word «задача» is not used
// in the product (D-40..D-44): «встреча», «поручение», «обработка».
// =============================================================================

// GLO-007 «Protocol» duplicated GLO-006 — merged, node removed.
MATCH (g:GlossaryTerm {id: 'GLO-007'}) DETACH DELETE g;

// GLO-001 — Meeting
MERGE (glo001:GlossaryTerm {id: 'GLO-001'})
SET glo001.name            = 'Meeting',
    glo001.name_ru         = 'Встреча',
    glo001.definition      = 'A single business meeting whose recording is uploaded into the system for processing. The root object that owns the resulting recording, transcript, and protocol throughout its lifecycle. In the UI and in all specifications the word «встреча» is the only name of this object; the word «задача» is never used for it.',
    glo001.aliases         = ['Встреча'],
    glo001.context         = 'Used throughout all processes (BP-001..BP-006); the top-level aggregate (OBJ-001).',
    glo001.status          = 'approved',
    glo001.created         = coalesce(glo001.created, date('2026-05-17')),
    glo001.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-001'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-001'}), (t:BusinessEntity {id: 'OBJ-001'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-002 — Recording
MERGE (glo002:GlossaryTerm {id: 'GLO-002'})
SET glo002.name            = 'Recording',
    glo002.name_ru         = 'Видеозапись',
    glo002.definition      = 'The video file uploaded by the Author that captures the meeting. The physical file is stored in object storage; the system tracks its metadata (filename, size, duration, storage path) as the Recording entity.',
    glo002.aliases         = ['Видеозапись', 'Запись', 'Video File'],
    glo002.context         = 'Created in BP-001 (Upload); consumed in BP-002 (Transcription). Corresponds to OBJ-002.',
    glo002.status          = 'approved',
    glo002.created         = coalesce(glo002.created, date('2026-05-17')),
    glo002.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-002'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-002'}), (t:BusinessEntity {id: 'OBJ-002'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-003 — Transcript
MERGE (glo003:GlossaryTerm {id: 'GLO-003'})
SET glo003.name            = 'Transcript',
    glo003.name_ru         = 'Транскрипт',
    glo003.definition      = 'The verbatim, speaker-attributed text output of the transcription pipeline. Contains the full spoken content of the meeting with speaker labels and timestamps per segment. Sometimes called a "verbatim transcript" to distinguish it from a summarized protocol.',
    glo003.aliases         = ['Транскрипт', 'Пословная транскрибация', 'Verbatim Transcript'],
    glo003.context         = 'Produced by BP-002 (Transcription); consumed by BP-003 (Retrieve) and BP-004 (Protocol Generation). Corresponds to OBJ-004.',
    glo003.status          = 'approved',
    glo003.created         = coalesce(glo003.created, date('2026-05-17')),
    glo003.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-003'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-003'}), (t:BusinessEntity {id: 'OBJ-004'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-004 — Speaker Diarization
MERGE (glo004:GlossaryTerm {id: 'GLO-004'})
SET glo004.name            = 'Speaker Diarization',
    glo004.name_ru         = 'Диаризация спикеров',
    glo004.definition      = 'The automated process of partitioning an audio stream into segments and labeling each segment with a speaker identity (e.g., «Спикер 1», «Спикер 2»). Diarization answers the question "who spoke when" and is a required step of the transcription pipeline.',
    glo004.aliases         = ['Диаризация спикеров', 'Diarization'],
    glo004.context         = 'Performed inside BP-002 (Transcription) by the ASR/Diarization Engine (EXT-01). Output feeds into speaker-attributed transcript segments.',
    glo004.status          = 'approved',
    glo004.created         = coalesce(glo004.created, date('2026-05-17')),
    glo004.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-004'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-004'}), (t:ExternalEntity {id: 'EXT-01'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-005 — Speaker Segment
MERGE (glo005:GlossaryTerm {id: 'GLO-005'})
SET glo005.name            = 'Speaker Segment',
    glo005.name_ru         = 'Сегмент транскрипта',
    glo005.definition      = 'A contiguous block of speech attributed to a single speaker, with a start timestamp, end timestamp, speaker label, and verbatim text. Multiple segments together form the full Transcript.',
    glo005.aliases         = ['Сегмент транскрипта', 'Transcript Segment'],
    glo005.context         = 'Produced by the diarization step inside BP-002; stored as structured content within OBJ-004 (Transcript) at MVP scope.',
    glo005.status          = 'approved',
    glo005.created         = coalesce(glo005.created, date('2026-05-17')),
    glo005.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-005'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-006 — Meeting Protocol
MERGE (glo006:GlossaryTerm {id: 'GLO-006'})
SET glo006.name            = 'Meeting Protocol',
    glo006.name_ru         = 'Протокол встречи',
    glo006.definition      = 'A structured summary document produced from the transcript by the LLM generation pipeline. Contains sections for meeting participants, discussion topics, decisions made, and action items with assignees and deadlines. Stored in Markdown and exportable to PDF.',
    glo006.aliases         = ['Протокол встречи', 'Протокол', 'Protocol', 'Minutes'],
    glo006.context         = 'Produced by BP-004; edited in BP-005; exported in BP-006. Corresponds to OBJ-006. Also used in the short form «Протокол» (former GLO-007, merged here).',
    glo006.status          = 'approved',
    glo006.created         = coalesce(glo006.created, date('2026-05-17')),
    glo006.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-006'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-006'}), (t:BusinessEntity {id: 'OBJ-006'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-008 — Action Item
MERGE (glo008:GlossaryTerm {id: 'GLO-008'})
SET glo008.name            = 'Action Item',
    glo008.name_ru         = 'Поручение',
    glo008.definition      = 'A commitment agreed at a meeting: an assignment to a named project participant with the meeting context and a deadline. Extracted by the LLM from the transcript; appears in the protocol section «## Задачи» and, in a project, as an entry of the project register (code T-n, status, assignee, due date, history of events). The word «задача» is not used in the product: the user-facing name is «поручение»; code identifiers (Task, /api/projects/:id/tasks, T-n) are unchanged.',
    glo008.aliases         = ['Поручение', 'Action Item'],
    glo008.context         = 'Protocol section of OBJ-006 (BP-004); project register ent-020 (Task) with change history ent-022 (TaskEvent).',
    glo008.status          = 'approved',
    glo008.created         = coalesce(glo008.created, date('2026-05-17')),
    glo008.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-008'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-008'}), (t:DomainEntity {id: 'ent-020'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-009 — Decision
MERGE (glo009:GlossaryTerm {id: 'GLO-009'})
SET glo009.name            = 'Decision',
    glo009.name_ru         = 'Решение',
    glo009.definition      = 'A conclusion or resolution reached during the meeting that is explicitly recorded in the protocol. Decisions are distinct from action items in that they represent outcomes rather than future tasks.',
    glo009.aliases         = ['Решение'],
    glo009.context         = 'Captured as a section within OBJ-006 (Protocol); extracted during BP-004 (Protocol Generation).',
    glo009.status          = 'approved',
    glo009.created         = coalesce(glo009.created, date('2026-05-17')),
    glo009.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-009'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-010 — Discussion Topic
MERGE (glo010:GlossaryTerm {id: 'GLO-010'})
SET glo010.name            = 'Discussion Topic',
    glo010.name_ru         = 'Тема обсуждения',
    glo010.definition      = 'A distinct agenda point or subject discussed during the meeting. The LLM groups related transcript content under topics, which become named sections within the protocol.',
    glo010.aliases         = ['Тема обсуждения', 'Вопрос', 'Agenda Item'],
    glo010.context         = 'Captured as a section within OBJ-006 (Protocol); extracted during BP-004 (Protocol Generation).',
    glo010.status          = 'approved',
    glo010.created         = coalesce(glo010.created, date('2026-05-17')),
    glo010.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-010'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-011 — Participant
MERGE (glo011:GlossaryTerm {id: 'GLO-011'})
SET glo011.name            = 'Participant',
    glo011.name_ru         = 'Участник',
    glo011.definition      = 'A person who took part in the meeting. Identified in the transcript through speaker labels (GLO-038) and, in a project, mapped to project participants (GLO-032). The participant list appears as a dedicated section of the protocol.',
    glo011.aliases         = ['Участник', 'Attendee'],
    glo011.context         = 'Derived from speaker segments in OBJ-004 (Transcript); surfaced in OBJ-006 (Protocol).',
    glo011.status          = 'approved',
    glo011.created         = coalesce(glo011.created, date('2026-05-17')),
    glo011.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-011'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-012 — Author
MERGE (glo012:GlossaryTerm {id: 'GLO-012'})
SET glo012.name            = 'Author',
    glo012.name_ru         = 'Автор',
    glo012.definition      = 'The business role of a workspace member who uploaded a meeting recording and owns the derived artifacts (transcript and protocol). Any member of the same workspace sees these artifacts (the workspace is the isolation unit).',
    glo012.aliases         = ['Автор', 'Uploader'],
    glo012.context         = 'Defined as ROL-01; performs BP-001, BP-003, BP-005, BP-006. Per FR-003 an Author is a User (GLO-027) acting inside a workspace (GLO-029).',
    glo012.status          = 'approved',
    glo012.created         = coalesce(glo012.created, date('2026-05-17')),
    glo012.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-012'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-012'}), (t:BusinessRole {id: 'ROL-01'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-013 — Reviewer
MERGE (glo013:GlossaryTerm {id: 'GLO-013'})
SET glo013.name            = 'Reviewer',
    glo013.name_ru         = 'Читатель протокола',
    glo013.definition      = 'A business role of a workspace member who reads, validates and gives feedback on a protocol produced by another member. Has no separate access rights: all workspace members see everything in the workspace.',
    glo013.aliases         = ['Читатель протокола', 'Проверяющий'],
    glo013.context         = 'Defined as ROL-02; same permissions as Author after FR-003 (access is defined by workspace membership). Feedback is captured as Protocol Feedback (GLO-045).',
    glo013.status          = 'approved',
    glo013.created         = coalesce(glo013.created, date('2026-05-17')),
    glo013.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-013'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-013'}), (t:BusinessRole {id: 'ROL-02'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-014 — Transcription Pipeline
MERGE (glo014:GlossaryTerm {id: 'GLO-014'})
SET glo014.name            = 'Transcription Pipeline',
    glo014.name_ru         = 'Пайплайн транскрибации',
    glo014.definition      = 'The end-to-end automated sequence of steps that transforms an uploaded video recording into a verbatim speaker-attributed transcript. Encompasses audio extraction, ASR, and speaker diarization.',
    glo014.aliases         = ['Пайплайн транскрибации', 'Transcription Flow'],
    glo014.context         = 'Corresponds to BP-002 (Transcribe Audio) and its constituent workflow steps.',
    glo014.status          = 'approved',
    glo014.created         = coalesce(glo014.created, date('2026-05-17')),
    glo014.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-014'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-014'}), (t:BusinessProcess {id: 'BP-002'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-015 — Protocol Lifecycle
MERGE (glo015:GlossaryTerm {id: 'GLO-015'})
SET glo015.name            = 'Protocol Lifecycle',
    glo015.name_ru         = 'Жизненный цикл протокола',
    glo015.definition      = 'The ordered sequence of states a Meeting Protocol passes through from generation to final export: generated → edited (zero or more times) → exported. Tracks how the document evolves after LLM creation.',
    glo015.aliases         = ['Жизненный цикл протокола'],
    glo015.context         = 'Spans BP-004 (generation), BP-005 (editing), BP-006 (export); states tracked via OBJ-006 and Meeting status OBJ-001.',
    glo015.status          = 'approved',
    glo015.created         = coalesce(glo015.created, date('2026-05-17')),
    glo015.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-015'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-016 — ASR
MERGE (glo016:GlossaryTerm {id: 'GLO-016'})
SET glo016.name            = 'ASR',
    glo016.name_ru         = 'Распознавание речи',
    glo016.definition      = 'Automatic Speech Recognition — the technology that converts audio speech into written text. In Transcrib, ASR is performed by an external engine (EXT-01) that also handles speaker diarization.',
    glo016.aliases         = ['Automatic Speech Recognition', 'Распознавание речи', 'Speech-to-Text', 'STT'],
    glo016.context         = 'Invoked inside BP-002 (Transcription); implemented by Deepgram Nova-3 behind IAsrProvider.',
    glo016.status          = 'approved',
    glo016.created         = coalesce(glo016.created, date('2026-05-17')),
    glo016.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-016'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-016'}), (t:ExternalEntity {id: 'EXT-01'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-017 — LLM
MERGE (glo017:GlossaryTerm {id: 'GLO-017'})
SET glo017.name            = 'LLM',
    glo017.name_ru         = 'Большая языковая модель',
    glo017.definition      = 'Large Language Model — an AI model used to summarize and structure the verbatim transcript into a formatted meeting protocol. The LLM receives a prompt containing the transcript and a template, and returns structured Markdown.',
    glo017.aliases         = ['Large Language Model', 'Большая языковая модель', 'Language Model'],
    glo017.context         = 'Invoked inside BP-004 (Protocol Generation) via EXT-02; production provider is OpenRouter (anthropic/claude-haiku-5.5) behind ILlmProvider, kie.ai is the fallback adapter.',
    glo017.status          = 'approved',
    glo017.created         = coalesce(glo017.created, date('2026-05-17')),
    glo017.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-017'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-017'}), (t:ExternalEntity {id: 'EXT-02'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-018 — Async Job
MERGE (glo018:GlossaryTerm {id: 'GLO-018'})
SET glo018.name            = 'Async Job',
    glo018.name_ru         = 'Обработка',
    glo018.definition      = 'A background operation that performs long-running work (transcription or protocol generation) outside the synchronous request-response cycle. The user sees its progress through meeting statuses and server-sent events and gets the result when processing completes. In the UI it is called «обработка».',
    glo018.aliases         = ['Обработка', 'Фоновая обработка', 'Background Job'],
    glo018.context         = 'Materialized as OBJ-003 (TranscriptionJob) and OBJ-005 (ProtocolGenerationJob).',
    glo018.status          = 'approved',
    glo018.created         = coalesce(glo018.created, date('2026-05-17')),
    glo018.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-018'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-019 — TranscriptionJob
MERGE (glo019:GlossaryTerm {id: 'GLO-019'})
SET glo019.name            = 'TranscriptionJob',
    glo019.name_ru         = 'Обработка распознавания',
    glo019.definition      = 'The specific async job record that tracks ASR and diarization pipeline execution for a single recording. Transitions through queued → in_progress → completed | failed, and is the primary means of surfacing transcription progress and errors to the system.',
    glo019.aliases         = ['Обработка распознавания'],
    glo019.context         = 'Created in BP-001; executed in BP-002. Corresponds to OBJ-003.',
    glo019.status          = 'approved',
    glo019.created         = coalesce(glo019.created, date('2026-05-17')),
    glo019.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-019'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-019'}), (t:BusinessEntity {id: 'OBJ-003'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-020 — ProtocolGenerationJob
MERGE (glo020:GlossaryTerm {id: 'GLO-020'})
SET glo020.name            = 'ProtocolGenerationJob',
    glo020.name_ru         = 'Обработка генерации протокола',
    glo020.definition      = 'The specific async job record that tracks LLM-based protocol generation for a single transcript. Created automatically when the TranscriptionJob completes; tracks prompt template version, timing, and failure details.',
    glo020.aliases         = ['Обработка генерации протокола'],
    glo020.context         = 'Triggered at end of BP-002; executed in BP-004. Corresponds to OBJ-005.',
    glo020.status          = 'approved',
    glo020.created         = coalesce(glo020.created, date('2026-05-17')),
    glo020.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-020'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-020'}), (t:BusinessEntity {id: 'OBJ-005'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-021 — Object Storage
MERGE (glo021:GlossaryTerm {id: 'GLO-021'})
SET glo021.name            = 'Object Storage',
    glo021.name_ru         = 'Объектное хранилище',
    glo021.definition      = 'A remote binary storage service used to persist large video files uploaded by the user. The system stores the file in object storage and records only the storage path reference in the Recording entity.',
    glo021.aliases         = ['Объектное хранилище', 'Blob Storage', 'File Storage'],
    glo021.context         = 'Corresponds to EXT-04; used in BP-001 (Upload) and BP-002 (Transcription); S3-compatible storage (MinIO locally, AWS S3/R2 in production).',
    glo021.status          = 'approved',
    glo021.created         = coalesce(glo021.created, date('2026-05-17')),
    glo021.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-021'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-021'}), (t:ExternalEntity {id: 'EXT-04'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-022 — Prompt Template
MERGE (glo022:GlossaryTerm {id: 'GLO-022'})
SET glo022.name            = 'Prompt Template',
    glo022.name_ru         = 'Шаблон промпта',
    glo022.definition      = 'A versioned template that defines the structure and instructions given to the LLM when generating a meeting protocol from a transcript. The template controls which sections (participants, topics, decisions, action items) the LLM must produce and in what format.',
    glo022.aliases         = ['Шаблон промпта', 'LLM Prompt'],
    glo022.context         = 'Used in BP-004 (Protocol Generation); version is recorded in OBJ-005 (ProtocolGenerationJob) for audit.',
    glo022.assumption_note = 'Template format and versioning mechanism are TBD at MVP; the term is recorded to ensure traceability of generation reproducibility.',
    glo022.status          = 'approved',
    glo022.created         = coalesce(glo022.created, date('2026-05-17')),
    glo022.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-022'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-023 — Markdown
MERGE (glo023:GlossaryTerm {id: 'GLO-023'})
SET glo023.name            = 'Markdown',
    glo023.name_ru         = 'Маркдаун',
    glo023.definition      = 'A lightweight text markup language used as the internal storage format for meeting protocols. The user edits the protocol as Markdown in the built-in editor; Markdown is also the source format for PDF export.',
    glo023.aliases         = ['Маркдаун'],
    glo023.context         = 'Stored in OBJ-006.markdown_content; edited in BP-005; exported in BP-006.',
    glo023.status          = 'approved',
    glo023.created         = coalesce(glo023.created, date('2026-05-17')),
    glo023.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-023'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-024 — PDF Export
MERGE (glo024:GlossaryTerm {id: 'GLO-024'})
SET glo024.name            = 'PDF Export',
    glo024.name_ru         = 'Экспорт в PDF',
    glo024.definition      = 'The on-demand conversion of a Markdown protocol document to a PDF file delivered to the user as a browser download. The PDF is a transient artifact — it is not persisted in the system after delivery.',
    glo024.aliases         = ['Экспорт в PDF', 'Export to PDF'],
    glo024.context         = 'Performed in BP-006 (Export Protocol to PDF); triggered by the Author.',
    glo024.status          = 'approved',
    glo024.created         = coalesce(glo024.created, date('2026-05-17')),
    glo024.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-024'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-024'}), (t:BusinessProcess {id: 'BP-006'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-025 — Upload
MERGE (glo025:GlossaryTerm {id: 'GLO-025'})
SET glo025.name            = 'Upload',
    glo025.name_ru         = 'Загрузка',
    glo025.definition      = 'The user action of submitting a video file to the system via the web interface. Upload initiates the meeting record creation and queues the transcription pipeline. Files up to 300–500 MB must be supported.',
    glo025.aliases         = ['Загрузка', 'File Upload'],
    glo025.context         = 'The first user action; corresponds to BP-001 (Upload Meeting Video).',
    glo025.status          = 'approved',
    glo025.created         = coalesce(glo025.created, date('2026-05-17')),
    glo025.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-025'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-025'}), (t:BusinessProcess {id: 'BP-001'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-026 — Language Hint
MERGE (glo026:GlossaryTerm {id: 'GLO-026'})
SET glo026.name            = 'Language Hint',
    glo026.name_ru         = 'Подсказка языка',
    glo026.definition      = 'An optional user-supplied indication of the primary spoken language in the recording (e.g., Russian, English, or auto-detect). The ASR engine uses this hint to improve transcription accuracy.',
    glo026.aliases         = ['Подсказка языка', 'Source Language', 'Language Setting'],
    glo026.context         = 'Stored as Meeting.language (OBJ-001-A03); supplied during BP-001 (Upload); passed to the ASR engine in BP-002.',
    glo026.assumption_note = 'The set of supported languages and whether auto-detection is accurate are TBD pending ASR vendor selection.',
    glo026.status          = 'approved',
    glo026.created         = coalesce(glo026.created, date('2026-05-17')),
    glo026.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-026'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-026'}), (t:BusinessEntity {id: 'OBJ-001'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-027 — User
MERGE (glo027:GlossaryTerm {id: 'GLO-027'})
SET glo027.name            = 'User',
    glo027.name_ru         = 'Пользователь',
    glo027.definition      = 'A person who signs in to Transcrib with a personal PIN and works inside the workspaces they are a member of (Membership): uploads meetings, reviews transcripts, edits and exports protocols. Accounts, workspaces and memberships are managed only by the operator through the CLI (SR-03).',
    glo027.aliases         = ['Пользователь', 'Член пространства'],
    glo027.context         = 'Workspace member (FR-003): plays the Author role (ROL-01) for the meetings they upload and may read other members\' meetings in the same workspace. Signs in via UC-400; the operator role SR-03 is not represented in the web UI.',
    glo027.status          = 'approved',
    glo027.created         = coalesce(glo027.created, date('2026-05-17')),
    glo027.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-027'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-027'}), (t:ExternalEntity {id: 'EXT-01'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-028 — Speaker Name Resolution
MERGE (glo028:GlossaryTerm {id: 'GLO-028'})
SET glo028.name            = 'Speaker Name Resolution',
    glo028.name_ru         = 'Определение имён спикеров',
    glo028.definition      = 'Post-diarization step that substitutes anonymous speaker labels («Спикер 1», «Спикер 2», ...) with real participant names. Names come from project participants or from the transcript itself (self-introductions, addressed names), and are confirmed by the user at the speaker confirmation step (GLO-037). Unresolved labels remain as «Спикер N».',
    glo028.aliases         = ['Определение имён спикеров', 'Подтверждение имён', 'Name Attribution'],
    glo028.context         = 'Performed inside BP-002 at step BP-002-S07B; results stored in Transcript.speaker_map (OBJ-004-A08). Confirmed by the user in UC-505 before protocol generation.',
    glo028.assumption_note = 'Resolution method (heuristic or LLM-based) and confidence threshold are TBD at SA phase.',
    glo028.status          = 'approved',
    glo028.created         = coalesce(glo028.created, date('2026-05-17')),
    glo028.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-028'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-028'}), (t:WorkflowStep {id: 'BP-002-S07B'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-029 — Workspace
MERGE (glo029:GlossaryTerm {id: 'GLO-029'})
SET glo029.name            = 'Workspace',
    glo029.name_ru         = 'Пространство',
    glo029.definition      = 'Единица изоляции данных: все члены пространства видят в нём все встречи, проекты и протоколы. У каждого пользователя есть личное пространство; общие выдаются по членству.',
    glo029.aliases         = ['Пространство', 'Рабочее пространство'],
    glo029.context         = 'ent-008; выбор пространства — UC-402; создаётся и выдаётся оператором через CLI (SR-03).',
    glo029.status          = 'approved',
    glo029.created         = coalesce(glo029.created, date('2026-05-17')),
    glo029.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-029'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-029'}), (t:DomainEntity {id: 'ent-008'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-030 — Membership
MERGE (glo030:GlossaryTerm {id: 'GLO-030'})
SET glo030.name            = 'Membership',
    glo030.name_ru         = 'Членство',
    glo030.definition      = 'Связь пользователя с пространством (уникальна по паре пользователь + пространство). Определяет, какие пространства видит пользователь. Выдаётся оператором через CLI.',
    glo030.aliases         = ['Членство', 'Доступ к пространству'],
    glo030.context         = 'ent-009; CLI user:grant / user:create --workspace.',
    glo030.status          = 'approved',
    glo030.created         = coalesce(glo030.created, date('2026-05-17')),
    glo030.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-030'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-030'}), (t:DomainEntity {id: 'ent-009'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-031 — Project
MERGE (glo031:GlossaryTerm {id: 'GLO-031'})
SET glo031.name            = 'Project',
    glo031.name_ru         = 'Проект',
    glo031.definition      = 'Группа встреч пространства с общим контекстом (участники проекта, термины проекта) и памятью проекта. Удаление проекта не удаляет встречи: у них пропадает только привязка к проекту.',
    glo031.aliases         = ['Проект'],
    glo031.context         = 'ent-012; UC-500, UC-501; FR-006.',
    glo031.status          = 'approved',
    glo031.created         = coalesce(glo031.created, date('2026-05-17')),
    glo031.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-031'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-031'}), (t:DomainEntity {id: 'ent-012'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-032 — Project Participant
MERGE (glo032:GlossaryTerm {id: 'GLO-032'})
SET glo032.name            = 'Project Participant',
    glo032.name_ru         = 'Участник проекта',
    glo032.definition      = 'Постоянный участник встреч проекта: имя, варианты написания и организация. Имена идут подсказкой в распознавание речи и в промпт протокола; метки спикеров сопоставляются с участниками проекта. Не путать с участником конкретной встречи (GLO-011).',
    glo032.aliases         = ['Участник проекта', 'Постоянный участник'],
    glo032.context         = 'ent-013; UC-501, UC-505.',
    glo032.status          = 'approved',
    glo032.created         = coalesce(glo032.created, date('2026-05-17')),
    glo032.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-032'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-032'}), (t:DomainEntity {id: 'ent-013'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-033 — Project Glossary Term
MERGE (glo033:GlossaryTerm {id: 'GLO-033'})
SET glo033.name            = 'Project Glossary Term',
    glo033.name_ru         = 'Термин проекта',
    glo033.definition      = 'Термин предметной области проекта, который помогает распознаванию и протоколу писать слова верно. Это данные продукта; не путать с глоссарием спецификации (узлы GlossaryTerm в графе, GLO-xxx), в котором описан этот словарь.',
    glo033.aliases         = ['Термин проекта', 'Термин глоссария проекта'],
    glo033.context         = 'ent-014 (таблица продукта, а не узел графа спецификации); UC-501.',
    glo033.status          = 'approved',
    glo033.created         = coalesce(glo033.created, date('2026-05-17')),
    glo033.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-033'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-033'}), (t:DomainEntity {id: 'ent-014'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-034 — Meeting Context
MERGE (glo034:GlossaryTerm {id: 'GLO-034'})
SET glo034.name            = 'Meeting Context',
    glo034.name_ru         = 'Контекст встречи',
    glo034.definition      = 'Необязательные сведения о конкретной встрече: проект, тип, цель, повестка, дополнительные участники и термины, предыдущий протокол, заметки. Заполняется при загрузке, фиксируется снимком при запуске распознавания.',
    glo034.aliases         = ['Контекст встречи'],
    glo034.context         = 'ent-015; UC-502, UC-504.',
    glo034.status          = 'approved',
    glo034.created         = coalesce(glo034.created, date('2026-05-17')),
    glo034.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-034'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-034'}), (t:DomainEntity {id: 'ent-015'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-035 — Context Snapshot
MERGE (glo035:GlossaryTerm {id: 'GLO-035'})
SET glo035.name            = 'Context Snapshot',
    glo035.name_ru         = 'Снимок контекста',
    glo035.definition      = 'Неизменяемая копия контекста встречи в момент запуска распознавания (карточка проекта + данные встречи + текст предыдущего протокола) с хэшем snapshot_hash. Правки проекта после запуска снимок не меняют; пользователь может посмотреть, какой контекст был использован.',
    glo035.aliases         = ['Снимок контекста', 'Использованный контекст'],
    glo035.context         = 'ent-015.snapshot_hash; UC-503, UC-504.',
    glo035.status          = 'approved',
    glo035.created         = coalesce(glo035.created, date('2026-05-17')),
    glo035.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-035'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-036 — Transcription Start
MERGE (glo036:GlossaryTerm {id: 'GLO-036'})
SET glo036.name            = 'Transcription Start',
    glo036.name_ru         = 'Запуск распознавания',
    glo036.definition      = 'Явное действие пользователя после загрузки: «Начать распознавание». До него встреча стоит в статусе AWAITING_START и контекст можно править; после — контекст фиксируется снимком и стартует обработка.',
    glo036.aliases         = ['Запуск распознавания', 'Начать распознавание', 'AWAITING_START'],
    glo036.context         = 'UC-503; статус встречи AWAITING_START.',
    glo036.status          = 'approved',
    glo036.created         = coalesce(glo036.created, date('2026-05-17')),
    glo036.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-036'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-037 — Speaker Confirmation
MERGE (glo037:GlossaryTerm {id: 'GLO-037'})
SET glo037.name            = 'Speaker Confirmation',
    glo037.name_ru         = 'Подтверждение спикеров',
    glo037.definition      = 'Шаг после распознавания и до генерации протокола: пользователь сопоставляет метки «Спикер N» с участниками проекта или именами (можно объединять дубли) либо пропускает шаг. До подтверждения встреча стоит в статусе AWAITING_SPEAKERS.',
    glo037.aliases         = ['Подтверждение спикеров', 'AWAITING_SPEAKERS'],
    glo037.context         = 'UC-505; FR-007; статус встречи AWAITING_SPEAKERS.',
    glo037.status          = 'approved',
    glo037.created         = coalesce(glo037.created, date('2026-05-17')),
    glo037.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-037'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-038 — Speaker
MERGE (glo038:GlossaryTerm {id: 'GLO-038'})
SET glo038.name            = 'Speaker',
    glo038.name_ru         = 'Спикер',
    glo038.definition      = 'Анонимная метка диаризации «Спикер N», присвоенная голосу в распознанной записи. Один человек может получить несколько меток; после подтверждения (GLO-037) метка заменяется именем участника. В коде метка хранится как SPEAKER_n; это идентификатор, пользователю он не показывается. Не синоним участника (GLO-011).',
    glo038.aliases         = ['Спикер', 'Метка спикера', 'Speaker label'],
    glo038.context         = 'Сегменты транскрипта OBJ-004; UC-505.',
    glo038.status          = 'approved',
    glo038.created         = coalesce(glo038.created, date('2026-05-17')),
    glo038.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-038'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-039 — Keyterm
MERGE (glo039:GlossaryTerm {id: 'GLO-039'})
SET glo039.name            = 'Keyterm',
    glo039.name_ru         = 'Ключевой термин',
    glo039.definition      = 'Слово или имя, которое передаётся распознаванию речи как подсказка: имена участников проекта первыми, затем термины проекта, не более 50. Повышает точность распознавания имён и терминов.',
    glo039.aliases         = ['Ключевой термин', 'Keyterm'],
    glo039.context         = 'ASR keyterms (Deepgram); ent-013, ent-014.',
    glo039.status          = 'approved',
    glo039.created         = coalesce(glo039.created, date('2026-05-17')),
    glo039.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-039'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-040 — Project Decision
MERGE (glo040:GlossaryTerm {id: 'GLO-040'})
SET glo040.name            = 'Project Decision',
    glo040.name_ru         = 'Решение проекта',
    glo040.definition      = 'Решение, принятое на встрече проекта и сохранённое в памяти проекта с кодом D-n, цитатой и связью с поручениями. Отличается от решения как раздела протокола (GLO-009): это запись реестра проекта, а не текст протокола.',
    glo040.aliases         = ['Решение проекта', 'D-n'],
    glo040.context         = 'ent-021; UC-604.',
    glo040.status          = 'approved',
    glo040.created         = coalesce(glo040.created, date('2026-05-17')),
    glo040.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-040'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-040'}), (t:DomainEntity {id: 'ent-021'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-041 — Action Item Event
MERGE (glo041:GlossaryTerm {id: 'GLO-041'})
SET glo041.name            = 'Action Item Event',
    glo041.name_ru         = 'Событие поручения',
    glo041.definition      = 'Изменение одного поля поручения (создание, упоминание, закрытие, смена исполнителя или срока, слияние), привязанное к встрече. Уверенные изменения применяются автоматически, остальные попадают в очередь подтверждения (GLO-042) с цитатой.',
    glo041.aliases         = ['Событие поручения', 'TaskEvent'],
    glo041.context         = 'ent-022; UC-601, UC-602, UC-603.',
    glo041.status          = 'approved',
    glo041.created         = coalesce(glo041.created, date('2026-05-17')),
    glo041.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-041'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-041'}), (t:DomainEntity {id: 'ent-022'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-042 — Confirmation Queue
MERGE (glo042:GlossaryTerm {id: 'GLO-042'})
SET glo042.name            = 'Confirmation Queue',
    glo042.name_ru         = 'Очередь подтверждения',
    glo042.definition      = 'Список событий поручений, которые модель предложила, но не применила сама (закрытие, отмена, слияние, смена исполнителя, неуверенные правки). Пользователь принимает или отклоняет каждое, видя цитату из встречи.',
    glo042.aliases         = ['Очередь подтверждения', 'Очередь на разбор'],
    glo042.context         = 'ent-022 (статус PENDING); UC-602.',
    glo042.status          = 'approved',
    glo042.created         = coalesce(glo042.created, date('2026-05-17')),
    glo042.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-042'})-[r:DEFINES_TERM]->() DELETE r;

// GLO-043 — Project Memory
MERGE (glo043:GlossaryTerm {id: 'GLO-043'})
SET glo043.name            = 'Project Memory',
    glo043.name_ru         = 'Память проекта',
    glo043.definition      = 'Накопленное знание проекта между встречами: версионируемая сводка, реестр поручений, решения. Обновляется после каждого протокола и подаётся в промпт следующего, без утечки чужих участников и контекста.',
    glo043.aliases         = ['Память проекта'],
    glo043.context         = 'ent-023; UC-600, UC-604; хранится в графе памяти.',
    glo043.status          = 'approved',
    glo043.created         = coalesce(glo043.created, date('2026-05-17')),
    glo043.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-043'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-043'}), (t:DomainEntity {id: 'ent-023'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-044 — Protocol Version
MERGE (glo044:GlossaryTerm {id: 'GLO-044'})
SET glo044.name            = 'Protocol Version',
    glo044.name_ru         = 'Версия протокола',
    glo044.definition      = 'Неизменяемая запись текста протокола: версия 1 создаётся генерацией, каждая правка пользователя добавляет следующую. Текущий текст остаётся в протоколе, история только пополняется.',
    glo044.aliases         = ['Версия протокола', 'История протокола'],
    glo044.context         = 'ent-017; UC-300, UC-301, UC-303.',
    glo044.status          = 'approved',
    glo044.created         = coalesce(glo044.created, date('2026-05-17')),
    glo044.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-044'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-044'}), (t:DomainEntity {id: 'ent-017'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-045 — Protocol Feedback
MERGE (glo045:GlossaryTerm {id: 'GLO-045'})
SET glo045.name            = 'Protocol Feedback',
    glo045.name_ru         = 'Обратная связь на протокол',
    glo045.definition      = 'Отзыв читателя на конкретную версию протокола: комментарий, исправленный текст или файл Word с правками. Файл разбирается и учитывается при следующей генерации.',
    glo045.aliases         = ['Обратная связь на протокол', 'Отзыв на протокол', 'Обратная связь'],
    glo045.context         = 'ent-018; UC-304, UC-305.',
    glo045.status          = 'approved',
    glo045.created         = coalesce(glo045.created, date('2026-05-17')),
    glo045.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-045'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-045'}), (t:DomainEntity {id: 'ent-018'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-046 — Protocol Generation
MERGE (glo046:GlossaryTerm {id: 'GLO-046'})
SET glo046.name            = 'Protocol Generation',
    glo046.name_ru         = 'Генерация протокола',
    glo046.definition      = 'Аудит одного прогона модели (протокол или обновление памяти): модель, версия промпта, снимок контекста, подсказки распознавания, расход токенов. Отвечает на вопрос, чем и из чего сделана версия протокола.',
    glo046.aliases         = ['Генерация протокола', 'Запуск генерации'],
    glo046.context         = 'ent-016; связан с OBJ-005 (GLO-020).',
    glo046.status          = 'approved',
    glo046.created         = coalesce(glo046.created, date('2026-05-17')),
    glo046.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-046'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-046'}), (t:DomainEntity {id: 'ent-016'}) MERGE (a)-[:DEFINES_TERM]->(t);

// GLO-047 — GraphOutbox
MERGE (glo047:GlossaryTerm {id: 'GLO-047'})
SET glo047.name            = 'GraphOutbox',
    glo047.name_ru         = 'Исходящая очередь графа',
    glo047.definition      = 'Служебная очередь в базе данных, из которой воркер переносит изменения (удаление встречи или проекта) в граф памяти проекта с повторами, пока граф недоступен. Пользователю не видна.',
    glo047.aliases         = ['Исходящая очередь графа', 'GraphOutbox'],
    glo047.context         = 'ent-019; UC-605.',
    glo047.status          = 'approved',
    glo047.created         = coalesce(glo047.created, date('2026-05-17')),
    glo047.updated         = date('2026-10-09');
MATCH (:GlossaryTerm {id: 'GLO-047'})-[r:DEFINES_TERM]->() DELETE r;
MATCH (a:GlossaryTerm {id: 'GLO-047'}), (t:DomainEntity {id: 'ent-019'}) MERGE (a)-[:DEFINES_TERM]->(t);

// =============================================================================
// END OF SEED
// =============================================================================
