// =============================================================================
// BA Handoff Seed — Transcrib
// Generated by: nacl-ba-handoff full
// Date: 2026-05-17
// Phase: BA -> SA
// =============================================================================
// Idempotent: all writes use MERGE. Safe to re-run.
// Does NOT re-create existing BA nodes (BusinessProcess, WorkflowStep,
// BusinessEntity, BusinessRule, Role). Only creates:
//   - 1 HandoffPackage node (HP-001)
//   - 1 stub WorkflowStep for BP-002-S07B (missing from prior seeds)
//   - 9 UCStub nodes (UC-001 .. UC-009)
//   - TRACES_TO relationships from automated WorkflowSteps to UCStubs
//   - TRACES_TO self-loop stubs on BusinessEntity and BusinessRule nodes
//     (recorded as property-only; no new SA nodes created)
// =============================================================================

// =============================================================================
// SECTION 0 — Missing WorkflowStep stub: BP-002-S07B
// This step is referenced in the BA model but was not written in
// ba-workflow-BP-002-seed.cypher. Creating it here so TRACES_TO links resolve.
// =============================================================================

MERGE (s07b:WorkflowStep {id: 'BP-002-S07B'})
SET s07b.name            = 'Resolve Speaker Names',
    s07b.description     = 'User (or system heuristic) maps anonymous speaker labels (SPEAKER_00, SPEAKER_01 …) produced by the diarization engine to real participant names. The mapping is stored and applied to all transcript segments before the transcript is considered complete.',
    s07b.stereotype      = 'automated',
    s07b.actor           = 'System / STK-01',
    s07b.artifact_name   = 'SpeakerNameMap',
    s07b.artifact_kind   = 'entity',
    s07b.assumption_note = 'ASSUMPTION: At MVP the mapping is user-supplied via a UI prompt after diarization completes. Fully automated name resolution (e.g., voice-print matching) is out of scope.',
    s07b.status          = 'draft',
    s07b.created         = date('2026-05-17'),
    s07b.updated         = date('2026-05-17');

MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (s07b:WorkflowStep   {id: 'BP-002-S07B'})
MERGE (bp002)-[:HAS_WORKFLOW_STEP]->(s07b);

// Place S07B between S07 and S08 in the sequence
MERGE (s07:WorkflowStep  {id: 'BP-002-S07'})
MERGE (s07b:WorkflowStep {id: 'BP-002-S07B'})
MERGE (s08:WorkflowStep  {id: 'BP-002-S08'})
MERGE (s07)-[:NEXT_STEP]->(s07b)
MERGE (s07b)-[:NEXT_STEP]->(s08);

// =============================================================================
// SECTION 1 — HandoffPackage HP-001
// =============================================================================

MERGE (hp:HandoffPackage {id: 'HP-001'})
SET hp.phase            = 'BA->SA',
    hp.status           = 'draft',
    hp.created          = date('2026-05-17'),
    hp.updated          = date('2026-05-17'),
    hp.summary          = 'BA phase complete for Transcrib. Covers 2 process groups (GPR-01, GPR-02), 6 business processes (BP-001..BP-006), 21 business rules (BRQ-001..BRQ-021), 6 business entities (OBJ-001..OBJ-006), 2 roles (ROL-01 Author, ROL-02 Reviewer). Produces 9 UC candidates and 6 SA module proposals for the SA phase.',

    // ---- UC candidates (JSON-like string for SA reference) ----
    hp.uc_candidates    = '[{"id":"UC-001","label":"Upload video and create meeting","source_bp":["BP-001"]},{"id":"UC-002","label":"Transcribe audio with diarization","source_bp":["BP-002"]},{"id":"UC-003","label":"Resolve speaker names in transcript","source_bp":["BP-002-S07B"]},{"id":"UC-004","label":"Generate meeting protocol via LLM","source_bp":["BP-004"]},{"id":"UC-005","label":"Handle transcription and protocol failures","source_bp":["BP-002-S09","BP-004-S10"]},{"id":"UC-006","label":"View and download transcript","source_bp":["BP-003"]},{"id":"UC-007","label":"Review and edit protocol in Markdown editor","source_bp":["BP-005"]},{"id":"UC-008","label":"Export protocol as PDF","source_bp":["BP-006"]},{"id":"UC-009","label":"Display meeting processing status","source_bp":["BP-001","BP-002","BP-004"]}]',

    // ---- Entity traceability (BA -> SA) ----
    hp.entity_traces    = '[{"ba_entity":"OBJ-001","ba_name":"Meeting","sa_entity":"Meeting"},{"ba_entity":"OBJ-002","ba_name":"Recording","sa_entity":"Recording"},{"ba_entity":"OBJ-003","ba_name":"TranscriptionJob","sa_entity":"TranscriptionJob"},{"ba_entity":"OBJ-004","ba_name":"Transcript","sa_entity":"Transcript"},{"ba_entity":"OBJ-005","ba_name":"ProtocolGenerationJob","sa_entity":"ProtocolGenerationJob"},{"ba_entity":"OBJ-006","ba_name":"Protocol","sa_entity":"Protocol"}]',

    // ---- Role traceability ----
    hp.role_traces      = '[{"ba_role":"ROL-01","ba_name":"Author","sa_role":"Author"},{"ba_role":"ROL-02","ba_name":"Reviewer","sa_role":"Reviewer"}]',

    // ---- Rule -> Requirement classification ----
    hp.rule_req_map     = '[{"brq":"BRQ-001","name":"File size limit","category":"FR","proposed_req":"REQ-001"},{"brq":"BRQ-002","name":"Allowed file formats","category":"FR","proposed_req":"REQ-002"},{"brq":"BRQ-003","name":"File integrity","category":"FR","proposed_req":"REQ-003"},{"brq":"BRQ-004","name":"Single active transcription job","category":"FR","proposed_req":"REQ-004"},{"brq":"BRQ-005","name":"Transcript immutability","category":"FR","proposed_req":"REQ-005"},{"brq":"BRQ-006","name":"Speaker label completeness","category":"FR","proposed_req":"REQ-006"},{"brq":"BRQ-007","name":"Minimum speaker segments","category":"FR","proposed_req":"REQ-007"},{"brq":"BRQ-008","name":"Protocol section completeness","category":"FR","proposed_req":"REQ-008"},{"brq":"BRQ-009","name":"Action item assignee required","category":"FR","proposed_req":"REQ-009"},{"brq":"BRQ-010","name":"Protocol edit authorization","category":"FR","proposed_req":"REQ-010"},{"brq":"BRQ-011","name":"Protocol versioning","category":"FR","proposed_req":"REQ-011"},{"brq":"BRQ-012","name":"PDF export fidelity","category":"FR","proposed_req":"REQ-012"},{"brq":"BRQ-013","name":"Language consistency","category":"FR","proposed_req":"REQ-013"},{"brq":"BRQ-014","name":"Transcription job timeout","category":"NFR","proposed_req":"REQ-014"},{"brq":"BRQ-015","name":"Protocol generation timeout","category":"NFR","proposed_req":"REQ-015"},{"brq":"BRQ-016","name":"Transcript download availability","category":"NFR","proposed_req":"REQ-016"},{"brq":"BRQ-017","name":"Concurrent upload limit","category":"NFR","proposed_req":"REQ-017"},{"brq":"BRQ-018","name":"Storage retention","category":"NFR","proposed_req":"REQ-018"},{"brq":"BRQ-019","name":"Upload progress feedback","category":"NFR","proposed_req":"REQ-019"},{"brq":"BRQ-020","name":"Status polling frequency","category":"NFR","proposed_req":"REQ-020"},{"brq":"BRQ-021","name":"Reviewer access scope","category":"FR","proposed_req":"REQ-021"}]',

    // ---- SA module proposals ----
    hp.sa_modules       = '[{"module":"Ingestion","description":"Upload, client-side validation, chunked transfer, object storage write, queue dispatch","source_bp":["BP-001"]},{"module":"TranscriptionPipeline","description":"ASR worker, audio extraction, diarization, speaker name resolution, transcript persistence","source_bp":["BP-002"]},{"module":"ProtocolGeneration","description":"LLM orchestration, prompt template management, response parsing, protocol persistence","source_bp":["BP-004"]},{"module":"ProtocolEditing","description":"Markdown editor UI, protocol versioning, save/discard","source_bp":["BP-005"]},{"module":"ExportDelivery","description":"Transcript download endpoint, PDF rendering and delivery","source_bp":["BP-003","BP-006"]},{"module":"MeetingStatus","description":"Cross-cutting status aggregation, real-time or polling-based status display for the Meeting lifecycle","source_bp":["BP-001","BP-002","BP-004"]}]',

    // ---- Open questions for SA ----
    hp.open_questions   = '[{"id":"OQ-1","question":"Speaker name resolution UX: does S07B require a synchronous UI prompt (blocking protocol generation) or an async mapping step the user completes later? This decision affects UC-003 flow and the TranscriptionPipeline module boundary."},{"id":"OQ-2","question":"Retry strategy for BP-002-S09 and BP-004-S10 (transcription and protocol failures): manual user-triggered retry vs. automatic back-off? This determines whether UC-005 needs a dedicated UI trigger or is purely informational."},{"id":"OQ-3","question":"Protocol versioning model (BRQ-011): is each edit a new immutable version (append-only log) or in-place overwrite with a single prior snapshot? This drives the SA domain model for Protocol and impacts UC-007 and ExportDelivery module design."}]';

// =============================================================================
// SECTION 2 — UCStub nodes (UC-001 .. UC-009)
// =============================================================================

MERGE (uc001:UCStub {id: 'UC-001'})
SET uc001.label       = 'Upload video and create meeting',
    uc001.description = 'User selects a video file, optionally sets a language hint, the system validates the file, uploads it to object storage, persists the Meeting and Recording records, and enqueues a TranscriptionJob.',
    uc001.source_bp   = 'BP-001',
    uc001.primary_actor = 'ROL-01',
    uc001.status      = 'candidate',
    uc001.created     = date('2026-05-17'),
    uc001.updated     = date('2026-05-17');

MERGE (uc002:UCStub {id: 'UC-002'})
SET uc002.label       = 'Transcribe audio with diarization',
    uc002.description = 'Automated pipeline: dequeue job, fetch video, extract audio, submit to ASR/diarization engine (EXT-02), receive speaker-attributed segments, assemble and persist Transcript.',
    uc002.source_bp   = 'BP-002',
    uc002.primary_actor = 'System',
    uc002.status      = 'candidate',
    uc002.created     = date('2026-05-17'),
    uc002.updated     = date('2026-05-17');

MERGE (uc003:UCStub {id: 'UC-003'})
SET uc003.label       = 'Resolve speaker names in transcript',
    uc003.description = 'User maps anonymous diarization speaker labels (SPEAKER_00 …) to real participant names. System applies the mapping to all transcript segments and marks the transcript name-resolved.',
    uc003.source_bp   = 'BP-002-S07B',
    uc003.primary_actor = 'ROL-01',
    uc003.status      = 'candidate',
    uc003.created     = date('2026-05-17'),
    uc003.updated     = date('2026-05-17');

MERGE (uc004:UCStub {id: 'UC-004'})
SET uc004.label       = 'Generate meeting protocol via LLM',
    uc004.description = 'Automated pipeline: receive transcript-ready event, load transcript, select prompt template by language, submit to LLM (EXT-03), parse response, validate sections, persist Protocol, update status to protocol-ready.',
    uc004.source_bp   = 'BP-004',
    uc004.primary_actor = 'System',
    uc004.status      = 'candidate',
    uc004.created     = date('2026-05-17'),
    uc004.updated     = date('2026-05-17');

MERGE (uc005:UCStub {id: 'UC-005'})
SET uc005.label       = 'Handle transcription and protocol failures',
    uc005.description = 'System marks a transcription or protocol generation job as failed, records the error reason, and surfaces the failure state in the UI. User may initiate retry (mechanism TBD at SA).',
    uc005.source_bp   = 'BP-002-S09,BP-004-S10',
    uc005.primary_actor = 'System',
    uc005.status      = 'candidate',
    uc005.created     = date('2026-05-17'),
    uc005.updated     = date('2026-05-17');

MERGE (uc006:UCStub {id: 'UC-006'})
SET uc006.label       = 'View and download transcript',
    uc006.description = 'User views the speaker-attributed transcript for a completed meeting and downloads it in a supported format.',
    uc006.source_bp   = 'BP-003',
    uc006.primary_actor = 'ROL-01',
    uc006.status      = 'candidate',
    uc006.created     = date('2026-05-17'),
    uc006.updated     = date('2026-05-17');

MERGE (uc007:UCStub {id: 'UC-007'})
SET uc007.label       = 'Review and edit protocol in Markdown editor',
    uc007.description = 'User (Author or Reviewer) opens the generated protocol in a Markdown editor, makes inline edits, and saves the revised version. Versioning behaviour is TBD (BRQ-011).',
    uc007.source_bp   = 'BP-005',
    uc007.primary_actor = 'ROL-01',
    uc007.status      = 'candidate',
    uc007.created     = date('2026-05-17'),
    uc007.updated     = date('2026-05-17');

MERGE (uc008:UCStub {id: 'UC-008'})
SET uc008.label       = 'Export protocol as PDF',
    uc008.description = 'User triggers PDF export of the current protocol version. System renders the Markdown to PDF and returns it as a downloadable file.',
    uc008.source_bp   = 'BP-006',
    uc008.primary_actor = 'ROL-01',
    uc008.status      = 'candidate',
    uc008.created     = date('2026-05-17'),
    uc008.updated     = date('2026-05-17');

MERGE (uc009:UCStub {id: 'UC-009'})
SET uc009.label       = 'Display meeting processing status',
    uc009.description = 'Cross-cutting: system surfaces the current pipeline state of a Meeting to the user (upload complete, transcribing, transcript ready, generating protocol, protocol ready, failed). Supports polling or real-time push.',
    uc009.source_bp   = 'BP-001,BP-002,BP-004',
    uc009.primary_actor = 'ROL-01',
    uc009.status      = 'candidate',
    uc009.created     = date('2026-05-17'),
    uc009.updated     = date('2026-05-17');

// =============================================================================
// SECTION 3 — Link HandoffPackage to UCStubs
// =============================================================================

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc001:UCStub {id: 'UC-001'})
MERGE (hp)-[:PROPOSES_UC]->(uc001);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc002:UCStub {id: 'UC-002'})
MERGE (hp)-[:PROPOSES_UC]->(uc002);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc003:UCStub {id: 'UC-003'})
MERGE (hp)-[:PROPOSES_UC]->(uc003);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc004:UCStub {id: 'UC-004'})
MERGE (hp)-[:PROPOSES_UC]->(uc004);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc005:UCStub {id: 'UC-005'})
MERGE (hp)-[:PROPOSES_UC]->(uc005);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc006:UCStub {id: 'UC-006'})
MERGE (hp)-[:PROPOSES_UC]->(uc006);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc007:UCStub {id: 'UC-007'})
MERGE (hp)-[:PROPOSES_UC]->(uc007);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc008:UCStub {id: 'UC-008'})
MERGE (hp)-[:PROPOSES_UC]->(uc008);

MERGE (hp:HandoffPackage {id: 'HP-001'})
MERGE (uc009:UCStub {id: 'UC-009'})
MERGE (hp)-[:PROPOSES_UC]->(uc009);

// =============================================================================
// SECTION 4 — TRACES_TO: WorkflowStep (automated) -> UCStub
// Only automated stereotype steps are UC candidates.
// decision / manual steps are excluded.
// =============================================================================

// --- UC-001: Upload video and create meeting (BP-001 automated steps) ---
// BP-001-S03-REJ  automated (show validation error)
// BP-001-S04      automated (upload file in chunks)
// BP-001-S05      automated (create recording + upload job records)
// BP-001-S06      automated (enqueue transcription job)
// BP-001-S07      automated (show upload confirmation)

MERGE (s:WorkflowStep {id: 'BP-001-S03-REJ'}) MERGE (uc:UCStub {id: 'UC-001'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-001', rationale: 'validation error display is system-automated UI behaviour'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-001-S04'})     MERGE (uc:UCStub {id: 'UC-001'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-001', rationale: 'core upload mechanism'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-001-S05'})     MERGE (uc:UCStub {id: 'UC-001'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-001', rationale: 'persistence of Meeting + Recording'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-001-S06'})     MERGE (uc:UCStub {id: 'UC-001'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-001', rationale: 'async job dispatch closes UC-001'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-001-S07'})     MERGE (uc:UCStub {id: 'UC-001'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-001', rationale: 'upload confirmation feedback'}]->(uc);

// --- UC-002: Transcribe audio with diarization (BP-002-S01..S08 happy path, excl. S07B) ---
MERGE (s:WorkflowStep {id: 'BP-002-S01'}) MERGE (uc:UCStub {id: 'UC-002'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-002', rationale: 'job dequeue starts pipeline'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S02'}) MERGE (uc:UCStub {id: 'UC-002'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-002', rationale: 'file fetch from storage'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S03'}) MERGE (uc:UCStub {id: 'UC-002'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-002', rationale: 'audio extraction'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S04'}) MERGE (uc:UCStub {id: 'UC-002'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-002', rationale: 'ASR/diarization submission'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S06'}) MERGE (uc:UCStub {id: 'UC-002'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-002', rationale: 'receive speaker segments (success path)'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S07'}) MERGE (uc:UCStub {id: 'UC-002'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-002', rationale: 'assemble and persist transcript'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S08'}) MERGE (uc:UCStub {id: 'UC-002'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-002', rationale: 'status update triggers BP-004'}]->(uc);

// --- UC-003: Resolve speaker names (BP-002-S07B — isolated distinct functionality) ---
MERGE (s:WorkflowStep {id: 'BP-002-S07B'}) MERGE (uc:UCStub {id: 'UC-003'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-003', rationale: 'speaker name mapping is a distinct user-facing interaction'}]->(uc);

// --- UC-004: Generate meeting protocol via LLM (BP-004 happy path) ---
MERGE (s:WorkflowStep {id: 'BP-004-S01'}) MERGE (uc:UCStub {id: 'UC-004'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-004', rationale: 'event receipt triggers protocol worker'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S02'}) MERGE (uc:UCStub {id: 'UC-004'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-004', rationale: 'transcript load'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S03'}) MERGE (uc:UCStub {id: 'UC-004'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-004', rationale: 'prompt template selection'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S04'}) MERGE (uc:UCStub {id: 'UC-004'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-004', rationale: 'LLM submission'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S06'}) MERGE (uc:UCStub {id: 'UC-004'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-004', rationale: 'LLM response parsing'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S08'}) MERGE (uc:UCStub {id: 'UC-004'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-004', rationale: 'protocol persistence'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S09'}) MERGE (uc:UCStub {id: 'UC-004'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-004', rationale: 'status update to protocol-ready closes UC-004'}]->(uc);

// --- UC-005: Handle failures (failure branch steps from BP-002 and BP-004) ---
MERGE (s:WorkflowStep {id: 'BP-002-S09'}) MERGE (uc:UCStub {id: 'UC-005'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-005', rationale: 'transcription failure handling'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S10'}) MERGE (uc:UCStub {id: 'UC-005'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-005', rationale: 'protocol generation failure handling'}]->(uc);

// --- UC-009: Meeting processing status (cross-cutting automated status updates) ---
// These steps also trace to UC-009 because they produce observable status transitions.
MERGE (s:WorkflowStep {id: 'BP-001-S07'}) MERGE (uc:UCStub {id: 'UC-009'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-009', rationale: 'upload-complete status visible in status view'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S08'}) MERGE (uc:UCStub {id: 'UC-009'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-009', rationale: 'transcript-ready status visible in status view'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-002-S09'}) MERGE (uc:UCStub {id: 'UC-009'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-009', rationale: 'transcription-failed status visible in status view'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S09'}) MERGE (uc:UCStub {id: 'UC-009'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-009', rationale: 'protocol-ready status visible in status view'}]->(uc);
MERGE (s:WorkflowStep {id: 'BP-004-S10'}) MERGE (uc:UCStub {id: 'UC-009'}) MERGE (s)-[:TRACES_TO {uc_candidate: 'UC-009', rationale: 'protocol-failed status visible in status view'}]->(uc);

// =============================================================================
// END OF SEED
// =============================================================================
