// =============================================================================
// BA Business Process Seed — Transcrib
// Generated by: nacl-ba-process full
// Date: 2026-05-17
// =============================================================================

// -----------------------------------------------------------------------------
// GPR-01 — Transcription Pipeline
// -----------------------------------------------------------------------------
MERGE (gpr01:ProcessGroup {id: 'GPR-01'})
SET gpr01.name        = 'Transcription Pipeline',
    gpr01.description = 'All processes from initial video upload through delivery of a verbatim, speaker-attributed transcript. Covers file handling, audio extraction, ASR/diarization, and transcript storage.',
    gpr01.status      = 'draft',
    gpr01.created     = date('2026-05-17'),
    gpr01.updated     = date('2026-05-17');

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (gpr01:ProcessGroup {id: 'GPR-01'})
MERGE (sc)-[:CONTAINS]->(gpr01);

// -----------------------------------------------------------------------------
// GPR-02 — Protocol Lifecycle
// -----------------------------------------------------------------------------
MERGE (gpr02:ProcessGroup {id: 'GPR-02'})
SET gpr02.name        = 'Protocol Lifecycle',
    gpr02.description = 'All processes that transform a completed transcript into a structured meeting protocol: LLM-based generation, in-app review and editing, and PDF export.',
    gpr02.status      = 'draft',
    gpr02.created     = date('2026-05-17'),
    gpr02.updated     = date('2026-05-17');

MERGE (sc:SystemContext {id: 'SYS-001'})
MERGE (gpr02:ProcessGroup {id: 'GPR-02'})
MERGE (sc)-[:CONTAINS]->(gpr02);

// =============================================================================
// BUSINESS PROCESSES
// =============================================================================

// -----------------------------------------------------------------------------
// BP-001 — Upload Meeting Video
// -----------------------------------------------------------------------------
MERGE (bp001:BusinessProcess {id: 'BP-001'})
SET bp001.name             = 'Upload Meeting Video',
    bp001.description      = 'User selects and uploads a meeting video file (300–500 MB) via the web interface. System validates the file, stores it in object storage, and enqueues an async transcription job.',
    bp001.trigger          = 'User initiates an upload action in the UI',
    bp001.owner            = 'STK-01',
    bp001.inputs           = ['Raw video file (300–500 MB, MP4/MKV/MOV or similar)'],
    bp001.outputs          = ['File stored in object storage (EXT-04)', 'Transcription job queued', 'Upload confirmation shown to user'],
    bp001.has_decomposition = true,
    bp001.status           = 'draft',
    bp001.created          = date('2026-05-17'),
    bp001.updated          = date('2026-05-17');

MERGE (gpr01:ProcessGroup {id: 'GPR-01'})
MERGE (bp001:BusinessProcess {id: 'BP-001'})
MERGE (gpr01)-[:CONTAINS]->(bp001);

// -----------------------------------------------------------------------------
// BP-002 — Transcribe Audio (ASR + Diarization)
// -----------------------------------------------------------------------------
MERGE (bp002:BusinessProcess {id: 'BP-002'})
SET bp002.name             = 'Transcribe Audio (ASR + Diarization)',
    bp002.description      = 'System retrieves the uploaded video from storage, extracts audio, submits it to the ASR/diarization engine (EXT-02), receives speaker-attributed transcript segments, assembles and persists the verbatim transcript.',
    bp002.trigger          = 'Transcription job is dequeued from the async processing queue',
    bp002.owner            = 'STK-01',
    bp002.inputs           = ['Video/audio file from object storage (EXT-04)', 'Speaker diarization request to ASR engine (EXT-02)'],
    bp002.outputs          = ['Verbatim speaker-attributed transcript with timestamps stored in the system', 'Processing status updated to "transcript ready"'],
    bp002.has_decomposition = true,
    bp002.status           = 'draft',
    bp002.assumption_note  = 'Audio extraction step (demux from video container) is treated as an internal sub-step, not a separate business process, because it has no business decision point.',
    bp002.created          = date('2026-05-17'),
    bp002.updated          = date('2026-05-17');

MERGE (gpr01:ProcessGroup {id: 'GPR-01'})
MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (gpr01)-[:CONTAINS]->(bp002);

// -----------------------------------------------------------------------------
// BP-003 — Download / Retrieve Transcript
// -----------------------------------------------------------------------------
MERGE (bp003:BusinessProcess {id: 'BP-003'})
SET bp003.name             = 'Download / Retrieve Transcript',
    bp003.description      = 'User views and downloads the completed verbatim transcript from the system. The transcript is rendered in the UI and offered as a downloadable text/document file.',
    bp003.trigger          = 'User navigates to transcript view and requests download',
    bp003.owner            = 'STK-01',
    bp003.inputs           = ['Persisted verbatim transcript (from BP-002)'],
    bp003.outputs          = ['Transcript file delivered to user (download)'],
    bp003.has_decomposition = false,
    bp003.status           = 'draft',
    bp003.assumption_note  = 'Treated as a simple retrieval/download operation. No complex branching; no separate workflow decomposition required at MVP scope.',
    bp003.created          = date('2026-05-17'),
    bp003.updated          = date('2026-05-17');

MERGE (gpr01:ProcessGroup {id: 'GPR-01'})
MERGE (bp003:BusinessProcess {id: 'BP-003'})
MERGE (gpr01)-[:CONTAINS]->(bp003);

// -----------------------------------------------------------------------------
// BP-004 — Generate Meeting Protocol (LLM)
// -----------------------------------------------------------------------------
MERGE (bp004:BusinessProcess {id: 'BP-004'})
SET bp004.name             = 'Generate Meeting Protocol',
    bp004.description      = 'System submits the verbatim transcript to the LLM protocol generator (EXT-03) with a structured extraction prompt. The LLM returns a meeting protocol (participants, topics, decisions, action items with assignees and deadlines). System persists the protocol as Markdown.',
    bp004.trigger          = 'Transcription job completes successfully (transcript is ready)',
    bp004.owner            = 'STK-01',
    bp004.inputs           = ['Verbatim speaker-attributed transcript (from BP-002)', 'Prompt template for structured protocol extraction'],
    bp004.outputs          = ['Meeting protocol stored as Markdown in the system', 'Processing status updated to "protocol ready"'],
    bp004.has_decomposition = true,
    bp004.status           = 'draft',
    bp004.assumption_note  = 'Protocol generation is triggered automatically after transcription completes; no manual user action is required to initiate it.',
    bp004.created          = date('2026-05-17'),
    bp004.updated          = date('2026-05-17');

MERGE (gpr02:ProcessGroup {id: 'GPR-02'})
MERGE (bp004:BusinessProcess {id: 'BP-004'})
MERGE (gpr02)-[:CONTAINS]->(bp004);

// -----------------------------------------------------------------------------
// BP-005 — Review and Edit Protocol
// -----------------------------------------------------------------------------
MERGE (bp005:BusinessProcess {id: 'BP-005'})
SET bp005.name             = 'Review and Edit Protocol',
    bp005.description      = 'User opens the generated protocol in the in-app Markdown editor, reviews its content, makes corrections or additions, and saves the updated version. The system persists the edited Markdown.',
    bp005.trigger          = 'User opens the protocol view and chooses to edit',
    bp005.owner            = 'STK-01',
    bp005.inputs           = ['Generated meeting protocol in Markdown (from BP-004 or previous edit)'],
    bp005.outputs          = ['Updated meeting protocol saved as Markdown'],
    bp005.has_decomposition = false,
    bp005.status           = 'draft',
    bp005.assumption_note  = 'Edit is free-form Markdown; no structured field validation is required at MVP scope. Save is a single user action.',
    bp005.created          = date('2026-05-17'),
    bp005.updated          = date('2026-05-17');

MERGE (gpr02:ProcessGroup {id: 'GPR-02'})
MERGE (bp005:BusinessProcess {id: 'BP-005'})
MERGE (gpr02)-[:CONTAINS]->(bp005);

// -----------------------------------------------------------------------------
// BP-006 — Export Protocol to PDF
// -----------------------------------------------------------------------------
MERGE (bp006:BusinessProcess {id: 'BP-006'})
SET bp006.name             = 'Export Protocol to PDF',
    bp006.description      = 'User requests a PDF export of the meeting protocol. System renders the Markdown to PDF via an export script and delivers the file to the user as a download.',
    bp006.trigger          = 'User clicks "Export to PDF" in the protocol view',
    bp006.owner            = 'STK-01',
    bp006.inputs           = ['Current meeting protocol Markdown (from BP-004 or BP-005)'],
    bp006.outputs          = ['PDF file delivered to user (download)'],
    bp006.has_decomposition = false,
    bp006.status           = 'draft',
    bp006.assumption_note  = 'PDF rendering uses a server-side export script (e.g. Pandoc or headless browser). The specific tool is TBD with the tech stack.',
    bp006.created          = date('2026-05-17'),
    bp006.updated          = date('2026-05-17');

MERGE (gpr02:ProcessGroup {id: 'GPR-02'})
MERGE (bp006:BusinessProcess {id: 'BP-006'})
MERGE (gpr02)-[:CONTAINS]->(bp006);

// =============================================================================
// INTER-PROCESS RELATIONSHIPS
// =============================================================================

// BP-001 triggers BP-002 — upload completion starts the async transcription job
MERGE (bp001:BusinessProcess {id: 'BP-001'})
MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (bp001)-[:TRIGGERS]->(bp002);

// BP-002 triggers BP-004 — transcript completion auto-triggers protocol generation
MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (bp004:BusinessProcess {id: 'BP-004'})
MERGE (bp002)-[:TRIGGERS]->(bp004);

// BP-003 depends on BP-002 — transcript must exist before retrieval
MERGE (bp003:BusinessProcess {id: 'BP-003'})
MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (bp003)-[:DEPENDS_ON]->(bp002);

// BP-005 depends on BP-004 — protocol must be generated before it can be edited
MERGE (bp005:BusinessProcess {id: 'BP-005'})
MERGE (bp004:BusinessProcess {id: 'BP-004'})
MERGE (bp005)-[:DEPENDS_ON]->(bp004);

// BP-006 depends on BP-004 — protocol must exist (generated or edited) before PDF export
MERGE (bp006:BusinessProcess {id: 'BP-006'})
MERGE (bp004:BusinessProcess {id: 'BP-004'})
MERGE (bp006)-[:DEPENDS_ON]->(bp004);
