// =============================================================================
// BA Business Rules Seed — Transcrib
// Generated by: nacl-ba-rules full
// Date: 2026-05-17
// =============================================================================

// =============================================================================
// BUSINESS RULES
// =============================================================================

// -----------------------------------------------------------------------------
// BRQ-001 — File size limit
// -----------------------------------------------------------------------------
MERGE (brq001:BusinessRule {id: 'BRQ-001'})
SET brq001.name            = 'File size limit',
    brq001.statement       = 'Recording.size_bytes MUST be less than or equal to 524288000 bytes (500 MB). Uploads exceeding this threshold are rejected before storage.',
    brq001.classification  = 'constraint',
    brq001.severity        = 'hard',
    brq001.rationale       = 'Prevents runaway object storage costs and ASR queue saturation from very large files at MVP scale.',
    brq001.status          = 'draft',
    brq001.created         = date('2026-05-17'),
    brq001.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-002 — Allowed file formats
// -----------------------------------------------------------------------------
MERGE (brq002:BusinessRule {id: 'BRQ-002'})
SET brq002.name            = 'Allowed file formats',
    brq002.statement       = 'Recording.mime_type MUST be one of {video/mp4, video/x-matroska, video/quicktime} (MP4, MKV, MOV). Any other MIME type causes the upload to be rejected.',
    brq002.classification  = 'constraint',
    brq002.severity        = 'hard',
    brq002.rationale       = 'The ASR pipeline supports audio extraction only from these container formats; accepting unsupported formats would cause silent pipeline failures.',
    brq002.status          = 'draft',
    brq002.created         = date('2026-05-17'),
    brq002.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-003 — File integrity
// -----------------------------------------------------------------------------
MERGE (brq003:BusinessRule {id: 'BRQ-003'})
SET brq003.name            = 'File integrity',
    brq003.statement       = 'The uploaded file MUST be a valid, non-corrupt video container that can be opened and from which audio can be extracted. Corrupt or unplayable files are rejected during the upload acceptance step.',
    brq003.classification  = 'constraint',
    brq003.severity        = 'hard',
    brq003.rationale       = 'Corrupt files would cause opaque failures deep inside the ASR pipeline; early validation produces a clearer user-facing error.',
    brq003.assumption_note = 'Validation method is TBD (e.g., FFprobe header check or short-duration probe decode). Full frame-level integrity is not guaranteed by MVP validation.',
    brq003.status          = 'draft',
    brq003.created         = date('2026-05-17'),
    brq003.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-004 — Supported languages
// -----------------------------------------------------------------------------
MERGE (brq004:BusinessRule {id: 'BRQ-004'})
SET brq004.name            = 'Supported languages',
    brq004.statement       = 'Meeting.language MUST be one of {ru, en, auto}. Any other value is rejected at input validation.',
    brq004.classification  = 'constraint',
    brq004.severity        = 'hard',
    brq004.rationale       = 'The ASR engine is configured and quality-tested only for Russian and English; limiting the enum prevents unexpected degradation for unsupported languages.',
    brq004.status          = 'draft',
    brq004.created         = date('2026-05-17'),
    brq004.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-005 — Auto-detect language fallback
// -----------------------------------------------------------------------------
MERGE (brq005:BusinessRule {id: 'BRQ-005'})
SET brq005.name            = 'Auto-detect language fallback',
    brq005.statement       = 'When Meeting.language = auto, the ASR engine selects the language during transcription; the detected language code MUST be recorded in Transcript.language upon job completion.',
    brq005.classification  = 'derivation',
    brq005.severity        = 'hard',
    brq005.rationale       = 'Downstream processes (protocol generation, PDF export) need a concrete language code; deriving it from the ASR output closes the information gap introduced by auto-detection.',
    brq005.status          = 'draft',
    brq005.created         = date('2026-05-17'),
    brq005.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-006 — One TranscriptionJob per Recording
// -----------------------------------------------------------------------------
MERGE (brq006:BusinessRule {id: 'BRQ-006'})
SET brq006.name            = 'One TranscriptionJob per Recording',
    brq006.statement       = 'A Recording MUST have exactly one TranscriptionJob. Creating a second TranscriptionJob for a Recording that already has one is prohibited.',
    brq006.classification  = 'invariant',
    brq006.severity        = 'hard',
    brq006.rationale       = 'The 1:1 relationship keeps the data model deterministic and prevents duplicate ASR costs and conflicting Transcript outputs.',
    brq006.status          = 'draft',
    brq006.created         = date('2026-05-17'),
    brq006.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-007 — Auto-trigger protocol generation
// -----------------------------------------------------------------------------
MERGE (brq007:BusinessRule {id: 'BRQ-007'})
SET brq007.name            = 'Auto-trigger protocol generation',
    brq007.statement       = 'When TranscriptionJob.status transitions to completed, a ProtocolGenerationJob MUST be created automatically for the resulting Transcript. No manual intervention is required or permitted between the two pipeline stages.',
    brq007.classification  = 'workflow',
    brq007.severity        = 'hard',
    brq007.rationale       = 'The seamless hand-off from transcription to protocol generation is a core system value; requiring a manual trigger would create an invisible gap in the user-facing status flow.',
    brq007.status          = 'draft',
    brq007.created         = date('2026-05-17'),
    brq007.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-008 — Meeting status mirrors pipeline stage
// -----------------------------------------------------------------------------
MERGE (brq008:BusinessRule {id: 'BRQ-008'})
SET brq008.name            = 'Meeting status mirrors pipeline stage',
    brq008.statement       = 'Meeting.status MUST be kept synchronized with the current pipeline stage at all times: uploading → transcribing → transcript_ready → protocol_generating → protocol_ready → edited | failed. No stage may be skipped.',
    brq008.classification  = 'invariant',
    brq008.severity        = 'hard',
    brq008.rationale       = 'Meeting.status is the single authoritative signal for the user-facing progress indicator; any divergence would cause misleading UI state.',
    brq008.status          = 'draft',
    brq008.created         = date('2026-05-17'),
    brq008.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-009 — Job terminal states are final
// -----------------------------------------------------------------------------
MERGE (brq009:BusinessRule {id: 'BRQ-009'})
SET brq009.name            = 'Job terminal states are final',
    brq009.statement       = 'Once TranscriptionJob.status or ProtocolGenerationJob.status reaches {completed, failed}, the status field MUST NOT be updated again. Terminal states are immutable.',
    brq009.classification  = 'invariant',
    brq009.severity        = 'hard',
    brq009.rationale       = 'Immutable terminal states enable reliable audit history and prevent race conditions from late-arriving worker callbacks.',
    brq009.status          = 'draft',
    brq009.created         = date('2026-05-17'),
    brq009.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-010 — Failure recorded with reason
// -----------------------------------------------------------------------------
MERGE (brq010:BusinessRule {id: 'BRQ-010'})
SET brq010.name            = 'Failure recorded with reason',
    brq010.statement       = 'When any job status is set to failed, the field error_reason MUST be non-null and MUST contain a human-readable description of the failure cause.',
    brq010.classification  = 'invariant',
    brq010.severity        = 'hard',
    brq010.rationale       = 'A structured error reason is required for user-facing error messages, support diagnostics, and pipeline monitoring. Silent failures are prohibited.',
    brq010.status          = 'draft',
    brq010.created         = date('2026-05-17'),
    brq010.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-011 — Required protocol sections
// -----------------------------------------------------------------------------
MERGE (brq011:BusinessRule {id: 'BRQ-011'})
SET brq011.name            = 'Required protocol sections',
    brq011.statement       = 'A Protocol MUST contain all four sections: Participants, Discussion Topics, Decisions, and Action Items. A protocol missing any of these sections is considered malformed and must not be persisted.',
    brq011.classification  = 'constraint',
    brq011.severity        = 'hard',
    brq011.rationale       = 'These four sections are the contractual output that users expect; partial protocols reduce trust in the generated artifact and block downstream use cases.',
    brq011.status          = 'draft',
    brq011.created         = date('2026-05-17'),
    brq011.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-012 — Action items should carry assignee and deadline
// -----------------------------------------------------------------------------
MERGE (brq012:BusinessRule {id: 'BRQ-012'})
SET brq012.name            = 'Action items should carry assignee and deadline',
    brq012.statement       = 'Each action item in the Protocol SHOULD include an assignee and a deadline where the information is extractable from the transcript. Omission is acceptable when the source material does not mention them.',
    brq012.classification  = 'constraint',
    brq012.severity        = 'soft',
    brq012.rationale       = 'Assignee and deadline make action items actionable; however, LLM extraction is best-effort and the transcript may genuinely lack this information.',
    brq012.assumption_note = 'The LLM prompt instructs the model to populate assignee and deadline when present. Accuracy depends on transcript quality and model capability. No post-generation validation of extraction completeness is performed at MVP.',
    brq012.status          = 'draft',
    brq012.created         = date('2026-05-17'),
    brq012.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-013 — Protocol language matches transcript
// -----------------------------------------------------------------------------
MERGE (brq013:BusinessRule {id: 'BRQ-013'})
SET brq013.name            = 'Protocol language matches transcript',
    brq013.statement       = 'The Protocol MUST be generated in the same language as its source Transcript (Transcript.language). The LLM prompt MUST specify this language explicitly.',
    brq013.classification  = 'constraint',
    brq013.severity        = 'hard',
    brq013.rationale       = 'A protocol in a different language than the meeting would be unusable; language consistency is a baseline quality requirement.',
    brq013.status          = 'draft',
    brq013.created         = date('2026-05-17'),
    brq013.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-014 — Protocol version increments on save
// -----------------------------------------------------------------------------
MERGE (brq014:BusinessRule {id: 'BRQ-014'})
SET brq014.name            = 'Protocol version increments on save',
    brq014.statement       = 'Protocol.version MUST be incremented by exactly 1 each time the user saves an edit in BP-005. The initial version after generation is 1; no save may decrement or skip a version number.',
    brq014.classification  = 'invariant',
    brq014.severity        = 'hard',
    brq014.rationale       = 'Monotonic versioning enables conflict detection, optimistic locking, and a clear audit trail of protocol evolution.',
    brq014.status          = 'draft',
    brq014.created         = date('2026-05-17'),
    brq014.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-015 — Edit count tracks saves
// -----------------------------------------------------------------------------
MERGE (brq015:BusinessRule {id: 'BRQ-015'})
SET brq015.name            = 'Edit count tracks saves',
    brq015.statement       = 'Protocol.edit_count MUST equal the total number of manual saves performed since the protocol was first generated. It starts at 0 and increments by 1 on each BP-005 save.',
    brq015.classification  = 'invariant',
    brq015.severity        = 'hard',
    brq015.rationale       = 'edit_count is a lightweight engagement metric distinguishing untouched auto-generated protocols from reviewed ones, useful for future analytics.',
    brq015.status          = 'draft',
    brq015.created         = date('2026-05-17'),
    brq015.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-016 — Author owns derived artifacts
// -----------------------------------------------------------------------------
MERGE (brq016:BusinessRule {id: 'BRQ-016'})
SET brq016.name            = 'Author owns derived artifacts',
    brq016.statement       = 'The Author (ROL-01) who created a Meeting is the sole owner of all derived artifacts for that Meeting: Recording (OBJ-002), Transcript (OBJ-004), and Protocol (OBJ-006). No other user may read, modify, or export these artifacts.',
    brq016.classification  = 'authorization',
    brq016.severity        = 'hard',
    brq016.rationale       = 'Meeting recordings may contain confidential business content; ownership isolation is the minimum access-control guarantee at MVP.',
    brq016.assumption_note = 'No authentication or session management is implemented at MVP. This rule is recorded as a forward-looking authorization constraint and is NOT technically enforced until a user identity mechanism is introduced.',
    brq016.status          = 'draft',
    brq016.created         = date('2026-05-17'),
    brq016.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-017 — PDF is transient
// -----------------------------------------------------------------------------
MERGE (brq017:BusinessRule {id: 'BRQ-017'})
SET brq017.name            = 'PDF is transient',
    brq017.statement       = 'The PDF generated during BP-006 MUST be delivered to the user as a file download and MUST NOT be persisted in the system. No PDF record or storage path is stored in the database.',
    brq017.classification  = 'invariant',
    brq017.severity        = 'hard',
    brq017.rationale       = 'Persisting PDFs would duplicate storage costs without business value; the canonical artifact is Protocol.markdown_content from which a PDF can always be regenerated on demand.',
    brq017.status          = 'draft',
    brq017.created         = date('2026-05-17'),
    brq017.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-018 — Markdown is canonical
// -----------------------------------------------------------------------------
MERGE (brq018:BusinessRule {id: 'BRQ-018'})
SET brq018.name            = 'Markdown is canonical',
    brq018.statement       = 'All protocol edits and PDF export operations MUST operate on Protocol.markdown_content as the single source of truth. No parallel representation (e.g., a rendered HTML copy) may diverge from the stored Markdown.',
    brq018.classification  = 'invariant',
    brq018.severity        = 'hard',
    brq018.rationale       = 'A single canonical format eliminates synchronisation bugs between rendered and stored representations and keeps the data model simple.',
    brq018.status          = 'draft',
    brq018.created         = date('2026-05-17'),
    brq018.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-019 — No SLA on processing time
// -----------------------------------------------------------------------------
MERGE (brq019:BusinessRule {id: 'BRQ-019'})
SET brq019.name            = 'No SLA on processing time',
    brq019.statement       = 'The system makes no maximum-time guarantee for transcription (BP-002) or protocol generation (BP-004). Users receive progress updates via status polling; no timeout-based failure is triggered by elapsed wall-clock time at MVP.',
    brq019.classification  = 'constraint',
    brq019.severity        = 'soft',
    brq019.rationale       = 'Processing time depends on third-party ASR and LLM services whose latency is outside system control. Defining an SLA without operational data would create false promises.',
    brq019.status          = 'draft',
    brq019.created         = date('2026-05-17'),
    brq019.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BRQ-020 — Recording retention until artifacts produced
// -----------------------------------------------------------------------------
MERGE (brq020:BusinessRule {id: 'BRQ-020'})
SET brq020.name            = 'Recording retention until artifacts produced',
    brq020.statement       = 'The original video file in object storage MUST be retained at least until both the Transcript and the Protocol for the same Meeting have been successfully produced. Deletion before that point is prohibited.',
    brq020.classification  = 'constraint',
    brq020.severity        = 'hard',
    brq020.rationale       = 'Retaining the source file allows pipeline re-runs on failure without requiring the user to re-upload. Retention policy beyond artifact completion is deferred.',
    brq020.assumption_note = 'Post-completion retention duration and deletion policy are TBD pending storage cost analysis. At MVP the file is retained indefinitely after artifact completion.',
    brq020.status          = 'draft',
    brq020.created         = date('2026-05-17'),
    brq020.updated         = date('2026-05-17');

// =============================================================================
// PROCESS → RULE RELATIONSHIPS  (HAS_RULE)
// =============================================================================

// BP-001 Upload Meeting Video
MERGE (bp001:BusinessProcess {id: 'BP-001'})
MERGE (brq001:BusinessRule   {id: 'BRQ-001'}) MERGE (bp001)-[:HAS_RULE]->(brq001)
MERGE (brq002:BusinessRule   {id: 'BRQ-002'}) MERGE (bp001)-[:HAS_RULE]->(brq002)
MERGE (brq003:BusinessRule   {id: 'BRQ-003'}) MERGE (bp001)-[:HAS_RULE]->(brq003)
MERGE (brq006:BusinessRule   {id: 'BRQ-006'}) MERGE (bp001)-[:HAS_RULE]->(brq006)
MERGE (brq020:BusinessRule   {id: 'BRQ-020'}) MERGE (bp001)-[:HAS_RULE]->(brq020);

// BP-002 Transcribe Audio
MERGE (bp002:BusinessProcess {id: 'BP-002'})
MERGE (brq005:BusinessRule   {id: 'BRQ-005'}) MERGE (bp002)-[:HAS_RULE]->(brq005)
MERGE (brq007:BusinessRule   {id: 'BRQ-007'}) MERGE (bp002)-[:HAS_RULE]->(brq007)
MERGE (brq008:BusinessRule   {id: 'BRQ-008'}) MERGE (bp002)-[:HAS_RULE]->(brq008)
MERGE (brq009:BusinessRule   {id: 'BRQ-009'}) MERGE (bp002)-[:HAS_RULE]->(brq009)
MERGE (brq010:BusinessRule   {id: 'BRQ-010'}) MERGE (bp002)-[:HAS_RULE]->(brq010)
MERGE (brq019:BusinessRule   {id: 'BRQ-019'}) MERGE (bp002)-[:HAS_RULE]->(brq019);

// BP-003 Download Transcript  (access/ownership rule applies)
MERGE (bp003:BusinessProcess {id: 'BP-003'})
MERGE (brq016:BusinessRule   {id: 'BRQ-016'}) MERGE (bp003)-[:HAS_RULE]->(brq016);

// BP-004 Generate Meeting Protocol
MERGE (bp004:BusinessProcess {id: 'BP-004'})
MERGE (brq009:BusinessRule   {id: 'BRQ-009'}) MERGE (bp004)-[:HAS_RULE]->(brq009)
MERGE (brq010:BusinessRule   {id: 'BRQ-010'}) MERGE (bp004)-[:HAS_RULE]->(brq010)
MERGE (brq011:BusinessRule   {id: 'BRQ-011'}) MERGE (bp004)-[:HAS_RULE]->(brq011)
MERGE (brq012:BusinessRule   {id: 'BRQ-012'}) MERGE (bp004)-[:HAS_RULE]->(brq012)
MERGE (brq013:BusinessRule   {id: 'BRQ-013'}) MERGE (bp004)-[:HAS_RULE]->(brq013)
MERGE (brq019:BusinessRule   {id: 'BRQ-019'}) MERGE (bp004)-[:HAS_RULE]->(brq019);

// BP-005 Review and Edit Protocol
MERGE (bp005:BusinessProcess {id: 'BP-005'})
MERGE (brq014:BusinessRule   {id: 'BRQ-014'}) MERGE (bp005)-[:HAS_RULE]->(brq014)
MERGE (brq015:BusinessRule   {id: 'BRQ-015'}) MERGE (bp005)-[:HAS_RULE]->(brq015)
MERGE (brq018:BusinessRule   {id: 'BRQ-018'}) MERGE (bp005)-[:HAS_RULE]->(brq018)
MERGE (brq016:BusinessRule   {id: 'BRQ-016'}) MERGE (bp005)-[:HAS_RULE]->(brq016);

// BP-006 Export Protocol to PDF
MERGE (bp006:BusinessProcess {id: 'BP-006'})
MERGE (brq017:BusinessRule   {id: 'BRQ-017'}) MERGE (bp006)-[:HAS_RULE]->(brq017)
MERGE (brq018:BusinessRule   {id: 'BRQ-018'}) MERGE (bp006)-[:HAS_RULE]->(brq018)
MERGE (brq016:BusinessRule   {id: 'BRQ-016'}) MERGE (bp006)-[:HAS_RULE]->(brq016);

// =============================================================================
// RULE → ENTITY RELATIONSHIPS  (APPLIES_TO)
// =============================================================================

// BRQ-001 — Recording.size_bytes
MERGE (brq001:BusinessRule {id: 'BRQ-001'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (brq001)-[:APPLIES_TO]->(obj002);

// BRQ-002 — Recording.mime_type
MERGE (brq002:BusinessRule {id: 'BRQ-002'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (brq002)-[:APPLIES_TO]->(obj002);

// BRQ-003 — Recording (integrity)
MERGE (brq003:BusinessRule {id: 'BRQ-003'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (brq003)-[:APPLIES_TO]->(obj002);

// BRQ-004 — Meeting.language
MERGE (brq004:BusinessRule {id: 'BRQ-004'})
MERGE (obj001:BusinessEntity {id: 'OBJ-001'}) MERGE (brq004)-[:APPLIES_TO]->(obj001);

// BRQ-005 — Meeting.language + Transcript.language
MERGE (brq005:BusinessRule {id: 'BRQ-005'})
MERGE (obj001:BusinessEntity {id: 'OBJ-001'}) MERGE (brq005)-[:APPLIES_TO]->(obj001);
MERGE (brq005:BusinessRule {id: 'BRQ-005'})
MERGE (obj004:BusinessEntity {id: 'OBJ-004'}) MERGE (brq005)-[:APPLIES_TO]->(obj004);

// BRQ-006 — Recording + TranscriptionJob (1:1)
MERGE (brq006:BusinessRule {id: 'BRQ-006'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (brq006)-[:APPLIES_TO]->(obj002);
MERGE (brq006:BusinessRule {id: 'BRQ-006'})
MERGE (obj003:BusinessEntity {id: 'OBJ-003'}) MERGE (brq006)-[:APPLIES_TO]->(obj003);

// BRQ-007 — TranscriptionJob + ProtocolGenerationJob (auto-trigger)
MERGE (brq007:BusinessRule {id: 'BRQ-007'})
MERGE (obj003:BusinessEntity {id: 'OBJ-003'}) MERGE (brq007)-[:APPLIES_TO]->(obj003);
MERGE (brq007:BusinessRule {id: 'BRQ-007'})
MERGE (obj005:BusinessEntity {id: 'OBJ-005'}) MERGE (brq007)-[:APPLIES_TO]->(obj005);

// BRQ-008 — Meeting.status
MERGE (brq008:BusinessRule {id: 'BRQ-008'})
MERGE (obj001:BusinessEntity {id: 'OBJ-001'}) MERGE (brq008)-[:APPLIES_TO]->(obj001);

// BRQ-009 — TranscriptionJob + ProtocolGenerationJob terminal states
MERGE (brq009:BusinessRule {id: 'BRQ-009'})
MERGE (obj003:BusinessEntity {id: 'OBJ-003'}) MERGE (brq009)-[:APPLIES_TO]->(obj003);
MERGE (brq009:BusinessRule {id: 'BRQ-009'})
MERGE (obj005:BusinessEntity {id: 'OBJ-005'}) MERGE (brq009)-[:APPLIES_TO]->(obj005);

// BRQ-010 — TranscriptionJob + ProtocolGenerationJob error_reason
MERGE (brq010:BusinessRule {id: 'BRQ-010'})
MERGE (obj003:BusinessEntity {id: 'OBJ-003'}) MERGE (brq010)-[:APPLIES_TO]->(obj003);
MERGE (brq010:BusinessRule {id: 'BRQ-010'})
MERGE (obj005:BusinessEntity {id: 'OBJ-005'}) MERGE (brq010)-[:APPLIES_TO]->(obj005);

// BRQ-011 — Protocol sections
MERGE (brq011:BusinessRule {id: 'BRQ-011'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq011)-[:APPLIES_TO]->(obj006);

// BRQ-012 — Protocol action items
MERGE (brq012:BusinessRule {id: 'BRQ-012'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq012)-[:APPLIES_TO]->(obj006);

// BRQ-013 — Protocol language
MERGE (brq013:BusinessRule {id: 'BRQ-013'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq013)-[:APPLIES_TO]->(obj006);
MERGE (brq013:BusinessRule {id: 'BRQ-013'})
MERGE (obj004:BusinessEntity {id: 'OBJ-004'}) MERGE (brq013)-[:APPLIES_TO]->(obj004);

// BRQ-014 — Protocol.version
MERGE (brq014:BusinessRule {id: 'BRQ-014'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq014)-[:APPLIES_TO]->(obj006);

// BRQ-015 — Protocol.edit_count
MERGE (brq015:BusinessRule {id: 'BRQ-015'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq015)-[:APPLIES_TO]->(obj006);

// BRQ-016 — Meeting + derived artifacts (authorization)
MERGE (brq016:BusinessRule {id: 'BRQ-016'})
MERGE (obj001:BusinessEntity {id: 'OBJ-001'}) MERGE (brq016)-[:APPLIES_TO]->(obj001);
MERGE (brq016:BusinessRule {id: 'BRQ-016'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (brq016)-[:APPLIES_TO]->(obj002);
MERGE (brq016:BusinessRule {id: 'BRQ-016'})
MERGE (obj004:BusinessEntity {id: 'OBJ-004'}) MERGE (brq016)-[:APPLIES_TO]->(obj004);
MERGE (brq016:BusinessRule {id: 'BRQ-016'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq016)-[:APPLIES_TO]->(obj006);

// BRQ-017 — Protocol (PDF transience)
MERGE (brq017:BusinessRule {id: 'BRQ-017'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq017)-[:APPLIES_TO]->(obj006);

// BRQ-018 — Protocol.markdown_content
MERGE (brq018:BusinessRule {id: 'BRQ-018'})
MERGE (obj006:BusinessEntity {id: 'OBJ-006'}) MERGE (brq018)-[:APPLIES_TO]->(obj006);

// BRQ-019 — No SLA (applies at process level only; no single entity)

// BRQ-020 — Recording retention
MERGE (brq020:BusinessRule {id: 'BRQ-020'})
MERGE (obj002:BusinessEntity {id: 'OBJ-002'}) MERGE (brq020)-[:APPLIES_TO]->(obj002);

// =============================================================================
// RULE → ATTRIBUTE RELATIONSHIPS  (CONSTRAINS)
// attribute-level refinements for the most precise rules
// =============================================================================

MERGE (brq001:BusinessRule    {id: 'BRQ-001'})
MERGE (a14:EntityAttribute    {id: 'OBJ-002-A04'})
MERGE (brq001)-[:CONSTRAINS]->(a14);

MERGE (brq002:BusinessRule    {id: 'BRQ-002'})
MERGE (a15:EntityAttribute    {id: 'OBJ-002-A05'})
MERGE (brq002)-[:CONSTRAINS]->(a15);

MERGE (brq004:BusinessRule    {id: 'BRQ-004'})
MERGE (a03:EntityAttribute    {id: 'OBJ-001-A03'})
MERGE (brq004)-[:CONSTRAINS]->(a03);

MERGE (brq005:BusinessRule    {id: 'BRQ-005'})
MERGE (a46:EntityAttribute    {id: 'OBJ-004-A06'})
MERGE (brq005)-[:CONSTRAINS]->(a46);

MERGE (brq008:BusinessRule    {id: 'BRQ-008'})
MERGE (a05:EntityAttribute    {id: 'OBJ-001-A05'})
MERGE (brq008)-[:CONSTRAINS]->(a05);

MERGE (brq014:BusinessRule    {id: 'BRQ-014'})
MERGE (a67:EntityAttribute    {id: 'OBJ-006-A07'})
MERGE (brq014)-[:CONSTRAINS]->(a67);

MERGE (brq015:BusinessRule    {id: 'BRQ-015'})
MERGE (a66:EntityAttribute    {id: 'OBJ-006-A06'})
MERGE (brq015)-[:CONSTRAINS]->(a66);

MERGE (brq018:BusinessRule    {id: 'BRQ-018'})
MERGE (a63:EntityAttribute    {id: 'OBJ-006-A03'})
MERGE (brq018)-[:CONSTRAINS]->(a63);
