// =============================================================================
// BA Workflow Seed — BP-004 Generate Meeting Protocol
// Generated by: nacl-ba-workflow
// Date: 2026-05-17
// =============================================================================

// =============================================================================
// WORKFLOW STEPS
// =============================================================================

// -----------------------------------------------------------------------------
// BP-004-S01 — Receive Transcript-Ready Event
// -----------------------------------------------------------------------------
MERGE (s01:WorkflowStep {id: 'BP-004-S01'})
SET s01.name            = 'Receive Transcript-Ready Event',
    s01.description     = 'Protocol worker is triggered by a transcript-ready domain event emitted when BP-002 completes successfully. The event carries the meeting ID used to locate the transcript.',
    s01.stereotype      = 'automated',
    s01.actor           = 'System',
    s01.artifact_name   = 'TranscriptReadyEvent',
    s01.artifact_kind   = 'event',
    s01.created         = date('2026-05-17'),
    s01.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S02 — Load Transcript
// -----------------------------------------------------------------------------
MERGE (s02:WorkflowStep {id: 'BP-004-S02'})
SET s02.name            = 'Load Transcript',
    s02.description     = 'Worker retrieves the verbatim speaker-attributed transcript from the data store using the meeting ID from the event payload.',
    s02.stereotype      = 'automated',
    s02.actor           = 'System',
    s02.artifact_name   = 'Transcript',
    s02.artifact_kind   = 'data',
    s02.created         = date('2026-05-17'),
    s02.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S03 — Select Prompt Template by Language
// -----------------------------------------------------------------------------
MERGE (s03:WorkflowStep {id: 'BP-004-S03'})
SET s03.name            = 'Select Prompt Template by Language',
    s03.description     = 'Worker detects the source language of the transcript (RU or EN) and loads the corresponding structured-extraction prompt template. The prompt instructs the LLM to produce the protocol in the same language as the source.',
    s03.stereotype      = 'automated',
    s03.actor           = 'System',
    s03.artifact_name   = 'PromptTemplate',
    s03.artifact_kind   = 'template',
    s03.assumption_note = 'Prompt template storage location and versioning strategy are TBD (embedded config, file store, or DB). Language detection relies on a lightweight heuristic or on metadata set during ASR.',
    s03.created         = date('2026-05-17'),
    s03.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S04 — Submit to LLM (EXT-03)
// -----------------------------------------------------------------------------
MERGE (s04:WorkflowStep {id: 'BP-004-S04'})
SET s04.name            = 'Submit Transcript + Prompt to LLM',
    s04.description     = 'Worker assembles an LLM request combining the transcript text and the selected prompt template, then submits the request to EXT-03 (LLM API). The request specifies required output sections: participants, discussed topics, decisions, action items with assignees and deadlines.',
    s04.stereotype      = 'automated',
    s04.actor           = 'EXT-03',
    s04.artifact_name   = 'LLMRequest',
    s04.artifact_kind   = 'api-payload',
    s04.created         = date('2026-05-17'),
    s04.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S05 — Decision: LLM Response Valid?
// -----------------------------------------------------------------------------
MERGE (s05:WorkflowStep {id: 'BP-004-S05'})
SET s05.name            = 'LLM Response Valid?',
    s05.description     = 'Worker inspects the LLM API response. Success path: HTTP 2xx with non-empty structured content. Failure path: HTTP error, timeout, or empty/malformed response body.',
    s05.stereotype      = 'decision',
    s05.actor           = 'System',
    s05.artifact_name   = 'LLMResponse',
    s05.artifact_kind   = 'api-payload',
    s05.created         = date('2026-05-17'),
    s05.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S06 — Parse LLM Response into Protocol Draft
// -----------------------------------------------------------------------------
MERGE (s06:WorkflowStep {id: 'BP-004-S06'})
SET s06.name            = 'Parse LLM Response into Protocol Draft',
    s06.description     = 'Worker parses the LLM output and maps it to a structured Markdown document with sections: Participants, Discussed Topics, Decisions Made, Action Items (assignee + deadline per item).',
    s06.stereotype      = 'automated',
    s06.actor           = 'System',
    s06.artifact_name   = 'ProtocolDraft',
    s06.artifact_kind   = 'document',
    s06.created         = date('2026-05-17'),
    s06.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S07 — Decision: All Required Sections Present?
// -----------------------------------------------------------------------------
MERGE (s07:WorkflowStep {id: 'BP-004-S07'})
SET s07.name            = 'All Required Sections Present?',
    s07.description     = 'Worker validates that the protocol draft contains all four required sections: Participants, Discussed Topics, Decisions Made, Action Items. Success path: all sections present. Failure path: one or more sections missing — treated as partial/malformed output.',
    s07.stereotype      = 'decision',
    s07.actor           = 'System',
    s07.artifact_name   = 'ProtocolDraft',
    s07.artifact_kind   = 'document',
    s07.assumption_note = 'A section is considered present if the heading exists and has at least one non-empty line of content. The threshold for "acceptable partial" output is TBD — for MVP any missing section routes to failure.',
    s07.created         = date('2026-05-17'),
    s07.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S08 — Persist Protocol as Markdown
// -----------------------------------------------------------------------------
MERGE (s08:WorkflowStep {id: 'BP-004-S08'})
SET s08.name            = 'Persist Protocol as Markdown',
    s08.description     = 'Worker writes the validated protocol draft to the data store as a Markdown document linked to the meeting record.',
    s08.stereotype      = 'automated',
    s08.actor           = 'System',
    s08.artifact_name   = 'Protocol',
    s08.artifact_kind   = 'document',
    s08.created         = date('2026-05-17'),
    s08.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S09 — Update Status to "Protocol Ready"
// -----------------------------------------------------------------------------
MERGE (s09:WorkflowStep {id: 'BP-004-S09'})
SET s09.name            = 'Update Status to Protocol Ready',
    s09.description     = 'Worker sets the meeting processing status to "protocol ready", making the protocol available for review in BP-005.',
    s09.stereotype      = 'automated',
    s09.actor           = 'System',
    s09.artifact_name   = 'MeetingStatus',
    s09.artifact_kind   = 'status',
    s09.created         = date('2026-05-17'),
    s09.updated         = date('2026-05-17');

// -----------------------------------------------------------------------------
// BP-004-S10 — Update Status to "Protocol Generation Failed"
// -----------------------------------------------------------------------------
MERGE (s10:WorkflowStep {id: 'BP-004-S10'})
SET s10.name            = 'Update Status to Protocol Generation Failed',
    s10.description     = 'Worker sets the meeting processing status to "protocol generation failed" so the error is surfaced to the user. The user may retry protocol generation manually.',
    s10.stereotype      = 'automated',
    s10.actor           = 'System',
    s10.artifact_name   = 'MeetingStatus',
    s10.artifact_kind   = 'status',
    s10.assumption_note = 'Retry mechanism (manual user-triggered or automatic with back-off) is TBD at SA phase. Error details are logged for diagnostics.',
    s10.created         = date('2026-05-17'),
    s10.updated         = date('2026-05-17');

// =============================================================================
// ATTACH STEPS TO BUSINESS PROCESS
// =============================================================================

MERGE (bp004:BusinessProcess {id: 'BP-004'})
MERGE (s01:WorkflowStep {id: 'BP-004-S01'})
MERGE (s02:WorkflowStep {id: 'BP-004-S02'})
MERGE (s03:WorkflowStep {id: 'BP-004-S03'})
MERGE (s04:WorkflowStep {id: 'BP-004-S04'})
MERGE (s05:WorkflowStep {id: 'BP-004-S05'})
MERGE (s06:WorkflowStep {id: 'BP-004-S06'})
MERGE (s07:WorkflowStep {id: 'BP-004-S07'})
MERGE (s08:WorkflowStep {id: 'BP-004-S08'})
MERGE (s09:WorkflowStep {id: 'BP-004-S09'})
MERGE (s10:WorkflowStep {id: 'BP-004-S10'})
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s01)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s02)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s03)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s04)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s05)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s06)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s07)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s08)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s09)
MERGE (bp004)-[:HAS_WORKFLOW_STEP]->(s10);

// =============================================================================
// HAPPY PATH SEQUENCE
// =============================================================================

MERGE (s01:WorkflowStep {id: 'BP-004-S01'})
MERGE (s02:WorkflowStep {id: 'BP-004-S02'})
MERGE (s01)-[:NEXT_STEP]->(s02);

MERGE (s02:WorkflowStep {id: 'BP-004-S02'})
MERGE (s03:WorkflowStep {id: 'BP-004-S03'})
MERGE (s02)-[:NEXT_STEP]->(s03);

MERGE (s03:WorkflowStep {id: 'BP-004-S03'})
MERGE (s04:WorkflowStep {id: 'BP-004-S04'})
MERGE (s03)-[:NEXT_STEP]->(s04);

MERGE (s04:WorkflowStep {id: 'BP-004-S04'})
MERGE (s05:WorkflowStep {id: 'BP-004-S05'})
MERGE (s04)-[:NEXT_STEP]->(s05);

// Decision S05: success branch
MERGE (s05:WorkflowStep {id: 'BP-004-S05'})
MERGE (s06:WorkflowStep {id: 'BP-004-S06'})
MERGE (s05)-[:NEXT_STEP {condition: 'valid response'}]->(s06);

MERGE (s06:WorkflowStep {id: 'BP-004-S06'})
MERGE (s07:WorkflowStep {id: 'BP-004-S07'})
MERGE (s06)-[:NEXT_STEP]->(s07);

// Decision S07: success branch
MERGE (s07:WorkflowStep {id: 'BP-004-S07'})
MERGE (s08:WorkflowStep {id: 'BP-004-S08'})
MERGE (s07)-[:NEXT_STEP {condition: 'all sections present'}]->(s08);

MERGE (s08:WorkflowStep {id: 'BP-004-S08'})
MERGE (s09:WorkflowStep {id: 'BP-004-S09'})
MERGE (s08)-[:NEXT_STEP]->(s09);

// =============================================================================
// FAILURE BRANCHES (HAS_DECISION)
// =============================================================================

// S05 failure: LLM error or timeout -> S10
MERGE (s05:WorkflowStep {id: 'BP-004-S05'})
MERGE (s10:WorkflowStep {id: 'BP-004-S10'})
MERGE (s05)-[:HAS_DECISION {condition: 'error or timeout', outcome: 'failure'}]->(s10);

// S07 failure: incomplete protocol draft -> S10
MERGE (s07:WorkflowStep {id: 'BP-004-S07'})
MERGE (s10:WorkflowStep {id: 'BP-004-S10'})
MERGE (s07)-[:HAS_DECISION {condition: 'missing required section', outcome: 'failure'}]->(s10);
